var hierarchy =
[
    [ "CE::Botones", "d0/dc8/class_c_e_1_1_botones.html", null ],
    [ "CE::Camara", "d4/d62/class_c_e_1_1_camara.html", [
      [ "CE::CamaraCuadro", "de/ded/class_c_e_1_1_camara_cuadro.html", null ],
      [ "CE::CamaraLERP", "da/dd2/class_c_e_1_1_camara_l_e_r_p.html", null ],
      [ "CE::CamaraSnapVentana", "d4/d21/class_c_e_1_1_camara_snap_ventana.html", null ]
    ] ],
    [ "CUSTOMVERTEX", "d6/d83/struct_c_u_s_t_o_m_v_e_r_t_e_x.html", null ],
    [ "sf::Drawable", null, [
      [ "CE::Objeto", "d0/d5b/class_c_e_1_1_objeto.html", [
        [ "IVJ::Entidad", "d6/d2a/class_i_v_j_1_1_entidad.html", null ],
        [ "IVJ::Figuras", "dd/d79/class_i_v_j_1_1_figuras.html", [
          [ "IVJ::Circulo", "db/d39/class_i_v_j_1_1_circulo.html", null ],
          [ "IVJ::Rectangulo", "d0/d8d/class_i_v_j_1_1_rectangulo.html", null ]
        ] ],
        [ "IVJ::Texto", "db/dea/class_i_v_j_1_1_texto.html", null ]
      ] ],
      [ "IVJ::TileMap", "dd/ddf/class_i_v_j_1_1_tile_map.html", null ]
    ] ],
    [ "CE::Escena", "d0/d51/class_c_e_1_1_escena.html", [
      [ "IVJ::Escena_Init", "d9/dad/class_i_v_j_1_1_escena___init.html", null ]
    ] ],
    [ "ExampleAppConsole", "de/d1c/struct_example_app_console.html", null ],
    [ "ExampleAppDocuments", "d0/d16/struct_example_app_documents.html", null ],
    [ "ExampleAppLog", "d1/db8/struct_example_app_log.html", null ],
    [ "ExampleAppPropertyEditor", "d8/da6/struct_example_app_property_editor.html", null ],
    [ "ExampleAsset", "de/d91/struct_example_asset.html", null ],
    [ "ExampleAssetsBrowser", "d4/d51/struct_example_assets_browser.html", null ],
    [ "ExampleDescriptorHeapAllocator", "df/da2/struct_example_descriptor_heap_allocator.html", null ],
    [ "ExampleDualListBox", "d0/d79/struct_example_dual_list_box.html", null ],
    [ "ExampleMemberInfo", "dc/dd0/struct_example_member_info.html", null ],
    [ "ExampleTreeNode", "d7/d95/struct_example_tree_node.html", null ],
    [ "FrameContext", "d7/d80/struct_frame_context.html", null ],
    [ "FrameResources", "da/d55/struct_frame_resources.html", null ],
    [ "IVJ::FSM", "d9/dba/class_i_v_j_1_1_f_s_m.html", null ],
    [ "CE::GameLayer", "da/d97/class_c_e_1_1_game_layer.html", [
      [ "IVJ::Juego", "d9/d5b/class_i_v_j_1_1_juego.html", null ]
    ] ],
    [ "CE::GestorAssets", "d7/d4a/class_c_e_1_1_gestor_assets.html", null ],
    [ "CE::GestorCamaras", "dc/d24/class_c_e_1_1_gestor_camaras.html", null ],
    [ "CE::GestorEscenas", "d0/d63/class_c_e_1_1_gestor_escenas.html", null ],
    [ "CE::GLayer", "d8/df9/class_c_e_1_1_g_layer.html", [
      [ "CE::GDock", "d2/dc3/class_c_e_1_1_g_dock.html", null ],
      [ "CE::GListaObjetos", "dc/d0a/class_c_e_1_1_g_lista_objetos.html", null ],
      [ "CE::GLogger", "d0/d8e/class_c_e_1_1_g_logger.html", null ],
      [ "CE::GPaths", "d9/d87/class_c_e_1_1_g_paths.html", null ],
      [ "CE::GPropiedades", "d1/d3a/class_c_e_1_1_g_propiedades.html", null ],
      [ "CE::GViewport", "d3/d15/class_c_e_1_1_g_viewport.html", null ]
    ] ],
    [ "GLFWgammaramp", "d8/d74/struct_g_l_f_wgammaramp.html", null ],
    [ "GLFWimage", "d5/d1f/struct_g_l_f_wimage.html", null ],
    [ "GLFWvidmode", "da/d9c/struct_g_l_f_wvidmode.html", null ],
    [ "CE::IComponentes", "db/d58/class_c_e_1_1_i_componentes.html", [
      [ "CE::IBoundingBox", "d2/d22/class_c_e_1_1_i_bounding_box.html", null ],
      [ "CE::IControl", "dd/d1b/class_c_e_1_1_i_control.html", null ],
      [ "CE::INombre", "d2/d35/class_c_e_1_1_i_nombre.html", null ],
      [ "CE::IPaths", "da/d77/class_c_e_1_1_i_paths.html", null ],
      [ "CE::IRespawn", "da/d77/class_c_e_1_1_i_respawn.html", null ],
      [ "CE::IShader", "d4/d4c/class_c_e_1_1_i_shader.html", null ],
      [ "CE::ISprite", "da/d2f/class_c_e_1_1_i_sprite.html", null ],
      [ "CE::IStats", "d8/dde/class_c_e_1_1_i_stats.html", null ],
      [ "CE::ITexto", "d4/d25/class_c_e_1_1_i_texto.html", null ],
      [ "CE::ITimer", "d9/d72/class_c_e_1_1_i_timer.html", null ],
      [ "CE::ITransform", "d5/d49/class_c_e_1_1_i_transform.html", null ],
      [ "IVJ::IInteractuable", "d6/db0/class_i_v_j_1_1_i_interactuable.html", [
        [ "IVJ::IDialogo", "d0/d10/class_i_v_j_1_1_i_dialogo.html", null ],
        [ "IVJ::IIndicador", "da/d14/class_i_v_j_1_1_i_indicador.html", null ]
      ] ],
      [ "IVJ::IMaquinaEstado", "d9/d98/class_i_v_j_1_1_i_maquina_estado.html", null ],
      [ "IVJ::IRayo", "d1/db4/class_i_v_j_1_1_i_rayo.html", null ],
      [ "IVJ::ITriangulo", "d5/d95/class_i_v_j_1_1_i_triangulo.html", null ]
    ] ],
    [ "CE::IIterador&lt; T &gt;", "df/d28/class_c_e_1_1_i_iterador.html", [
      [ "CE::Lista< T >", "d7/d15/class_c_e_1_1_lista.html", null ]
    ] ],
    [ "CE::IIterador&lt; std::pair&lt; std::string, Niveles &gt; &gt;", "df/d28/class_c_e_1_1_i_iterador.html", [
      [ "CE::Lista< std::pair< std::string, Niveles > >", "d7/d15/class_c_e_1_1_lista.html", null ]
    ] ],
    [ "CE::IManipularDatos&lt; T &gt;", "de/d1b/class_c_e_1_1_i_manipular_datos.html", [
      [ "CE::Lista< T >", "d7/d15/class_c_e_1_1_lista.html", null ]
    ] ],
    [ "CE::IManipularDatos&lt; std::pair&lt; std::string, Niveles &gt; &gt;", "de/d1b/class_c_e_1_1_i_manipular_datos.html", [
      [ "CE::Lista< std::pair< std::string, Niveles > >", "d7/d15/class_c_e_1_1_lista.html", null ]
    ] ],
    [ "ImBitArray&lt; BITCOUNT, OFFSET &gt;", "d6/d40/struct_im_bit_array.html", null ],
    [ "ImBitVector", "d6/d28/struct_im_bit_vector.html", null ],
    [ "ImChunkStream&lt; T &gt;", "d0/d05/struct_im_chunk_stream.html", null ],
    [ "ImColor", "db/da3/struct_im_color.html", null ],
    [ "ImDrawChannel", "df/d94/struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "d6/d65/struct_im_draw_cmd.html", null ],
    [ "ImDrawCmdHeader", "d0/de9/struct_im_draw_cmd_header.html", null ],
    [ "ImDrawData", "d9/d78/struct_im_draw_data.html", null ],
    [ "ImDrawDataBuilder", "de/d11/struct_im_draw_data_builder.html", null ],
    [ "ImDrawList", "dd/d30/struct_im_draw_list.html", null ],
    [ "ImDrawListSharedData", "dd/d70/struct_im_draw_list_shared_data.html", null ],
    [ "ImDrawListSplitter", "d4/de1/struct_im_draw_list_splitter.html", null ],
    [ "ImDrawVert", "dc/d86/struct_im_draw_vert.html", null ],
    [ "ImDrawVertAllegro", "db/dae/struct_im_draw_vert_allegro.html", null ],
    [ "ImFont", "d7/dc9/struct_im_font.html", null ],
    [ "ImFontAtlas", "d5/d9e/struct_im_font_atlas.html", null ],
    [ "ImFontAtlasCustomRect", "d1/d27/struct_im_font_atlas_custom_rect.html", null ],
    [ "ImFontBuildDstData", "d4/d3b/struct_im_font_build_dst_data.html", null ],
    [ "ImFontBuildDstDataFT", "d0/deb/struct_im_font_build_dst_data_f_t.html", null ],
    [ "ImFontBuilderIO", "d3/d0e/struct_im_font_builder_i_o.html", null ],
    [ "ImFontBuildSrcData", "d0/d98/struct_im_font_build_src_data.html", null ],
    [ "ImFontBuildSrcDataFT", "dd/dff/struct_im_font_build_src_data_f_t.html", null ],
    [ "ImFontBuildSrcGlyphFT", "db/d4e/struct_im_font_build_src_glyph_f_t.html", null ],
    [ "ImFontConfig", "d5/d84/struct_im_font_config.html", null ],
    [ "ImFontGlyph", "df/d57/struct_im_font_glyph.html", null ],
    [ "ImFontGlyphRangesBuilder", "d4/d56/struct_im_font_glyph_ranges_builder.html", null ],
    [ "ImGL3WProcs", "d4/d6c/union_im_g_l3_w_procs.html", null ],
    [ "ImGui_ImplAllegro5_Data", "d4/d33/struct_im_gui___impl_allegro5___data.html", null ],
    [ "ImGui_ImplDX10_Data", "dd/d9e/struct_im_gui___impl_d_x10___data.html", null ],
    [ "ImGui_ImplDX10_RenderState", "d4/d80/struct_im_gui___impl_d_x10___render_state.html", null ],
    [ "ImGui_ImplDX10_ViewportData", "db/dfc/struct_im_gui___impl_d_x10___viewport_data.html", null ],
    [ "ImGui_ImplDX11_Data", "d1/d6d/struct_im_gui___impl_d_x11___data.html", null ],
    [ "ImGui_ImplDX11_RenderState", "db/dbf/struct_im_gui___impl_d_x11___render_state.html", null ],
    [ "ImGui_ImplDX11_ViewportData", "d9/d2c/struct_im_gui___impl_d_x11___viewport_data.html", null ],
    [ "ImGui_ImplDX12_Data", "d3/dcd/struct_im_gui___impl_d_x12___data.html", null ],
    [ "ImGui_ImplDX12_FrameContext", "dd/d05/struct_im_gui___impl_d_x12___frame_context.html", null ],
    [ "ImGui_ImplDX12_InitInfo", "d0/df5/struct_im_gui___impl_d_x12___init_info.html", null ],
    [ "ImGui_ImplDX12_RenderBuffers", "d4/dc1/struct_im_gui___impl_d_x12___render_buffers.html", null ],
    [ "ImGui_ImplDX12_RenderState", "d3/db6/struct_im_gui___impl_d_x12___render_state.html", null ],
    [ "ImGui_ImplDX12_Texture", "dc/d64/struct_im_gui___impl_d_x12___texture.html", null ],
    [ "ImGui_ImplDX12_ViewportData", "d5/d89/struct_im_gui___impl_d_x12___viewport_data.html", null ],
    [ "ImGui_ImplDX9_Data", "db/d07/struct_im_gui___impl_d_x9___data.html", null ],
    [ "ImGui_ImplDX9_ViewportData", "d5/d9e/struct_im_gui___impl_d_x9___viewport_data.html", null ],
    [ "ImGui_ImplGlfw_Data", "d5/d6e/struct_im_gui___impl_glfw___data.html", null ],
    [ "ImGui_ImplGlfw_ViewportData", "d2/d04/struct_im_gui___impl_glfw___viewport_data.html", null ],
    [ "ImGui_ImplMetal_Data", "d0/dda/struct_im_gui___impl_metal___data.html", null ],
    [ "ImGui_ImplOpenGL2_Data", "d5/d7a/struct_im_gui___impl_open_g_l2___data.html", null ],
    [ "ImGui_ImplOpenGL3_Data", "dc/d45/struct_im_gui___impl_open_g_l3___data.html", null ],
    [ "ImGui_ImplOSX_Data", "d2/d61/struct_im_gui___impl_o_s_x___data.html", null ],
    [ "ImGui_ImplSDL2_Data", "de/d4e/struct_im_gui___impl_s_d_l2___data.html", null ],
    [ "ImGui_ImplSDL2_ViewportData", "d3/de7/struct_im_gui___impl_s_d_l2___viewport_data.html", null ],
    [ "ImGui_ImplSDL3_Data", "dc/de5/struct_im_gui___impl_s_d_l3___data.html", null ],
    [ "ImGui_ImplSDL3_ViewportData", "d9/dc3/struct_im_gui___impl_s_d_l3___viewport_data.html", null ],
    [ "ImGui_ImplSDLGPU3_Data", "d7/dfe/struct_im_gui___impl_s_d_l_g_p_u3___data.html", null ],
    [ "ImGui_ImplSDLGPU3_FrameData", "d7/de3/struct_im_gui___impl_s_d_l_g_p_u3___frame_data.html", null ],
    [ "ImGui_ImplSDLGPU3_InitInfo", "d8/d4e/struct_im_gui___impl_s_d_l_g_p_u3___init_info.html", null ],
    [ "ImGui_ImplSDLRenderer2_Data", "d1/d05/struct_im_gui___impl_s_d_l_renderer2___data.html", null ],
    [ "ImGui_ImplSDLRenderer2_RenderState", "da/d7d/struct_im_gui___impl_s_d_l_renderer2___render_state.html", null ],
    [ "ImGui_ImplSDLRenderer3_Data", "df/d54/struct_im_gui___impl_s_d_l_renderer3___data.html", null ],
    [ "ImGui_ImplSDLRenderer3_RenderState", "d0/d19/struct_im_gui___impl_s_d_l_renderer3___render_state.html", null ],
    [ "ImGui_ImplVulkan_Data", "d2/d86/struct_im_gui___impl_vulkan___data.html", null ],
    [ "ImGui_ImplVulkan_FrameRenderBuffers", "d4/d27/struct_im_gui___impl_vulkan___frame_render_buffers.html", null ],
    [ "ImGui_ImplVulkan_InitInfo", "de/d2c/struct_im_gui___impl_vulkan___init_info.html", null ],
    [ "ImGui_ImplVulkan_RenderState", "d6/db6/struct_im_gui___impl_vulkan___render_state.html", null ],
    [ "ImGui_ImplVulkan_Texture", "da/db3/struct_im_gui___impl_vulkan___texture.html", null ],
    [ "ImGui_ImplVulkan_ViewportData", "d1/dca/struct_im_gui___impl_vulkan___viewport_data.html", null ],
    [ "ImGui_ImplVulkan_WindowRenderBuffers", "d4/d6d/struct_im_gui___impl_vulkan___window_render_buffers.html", null ],
    [ "ImGui_ImplVulkanH_Frame", "d6/df7/struct_im_gui___impl_vulkan_h___frame.html", null ],
    [ "ImGui_ImplVulkanH_FrameSemaphores", "d5/d82/struct_im_gui___impl_vulkan_h___frame_semaphores.html", null ],
    [ "ImGui_ImplVulkanH_Window", "de/d27/struct_im_gui___impl_vulkan_h___window.html", null ],
    [ "ImGui_ImplWGPU_Data", "df/d96/struct_im_gui___impl_w_g_p_u___data.html", null ],
    [ "ImGui_ImplWGPU_InitInfo", "dd/d00/struct_im_gui___impl_w_g_p_u___init_info.html", null ],
    [ "ImGui_ImplWGPU_RenderState", "da/d0a/struct_im_gui___impl_w_g_p_u___render_state.html", null ],
    [ "ImGui_ImplWin32_Data", "d5/d71/struct_im_gui___impl_win32___data.html", null ],
    [ "ImGui_ImplWin32_ViewportData", "d5/d40/struct_im_gui___impl_win32___viewport_data.html", null ],
    [ "ImGuiBoxSelectState", "dd/d35/struct_im_gui_box_select_state.html", null ],
    [ "ImGuiColorMod", "da/d8e/struct_im_gui_color_mod.html", null ],
    [ "ImGuiComboPreviewData", "d7/d3a/struct_im_gui_combo_preview_data.html", null ],
    [ "ImGuiContext", "d7/da3/struct_im_gui_context.html", null ],
    [ "ImGuiContextHook", "df/dbc/struct_im_gui_context_hook.html", null ],
    [ "ImGuiDataTypeInfo", "d5/dbe/struct_im_gui_data_type_info.html", null ],
    [ "ImGuiDataTypeStorage", "de/d93/struct_im_gui_data_type_storage.html", null ],
    [ "ImGuiDeactivatedItemData", "de/d87/struct_im_gui_deactivated_item_data.html", null ],
    [ "ImGuiDebugAllocEntry", "dd/d28/struct_im_gui_debug_alloc_entry.html", null ],
    [ "ImGuiDebugAllocInfo", "d2/d45/struct_im_gui_debug_alloc_info.html", null ],
    [ "ImGuiDemoWindowData", "dc/d71/struct_im_gui_demo_window_data.html", null ],
    [ "ImGuiDockContext", "d1/dcf/struct_im_gui_dock_context.html", null ],
    [ "ImGuiDockContextPruneNodeData", "de/db6/struct_im_gui_dock_context_prune_node_data.html", null ],
    [ "ImGuiDockNode", "dd/dcf/struct_im_gui_dock_node.html", null ],
    [ "ImGuiDockNodeSettings", "d2/d29/struct_im_gui_dock_node_settings.html", null ],
    [ "ImGuiDockNodeTreeInfo", "df/dca/struct_im_gui_dock_node_tree_info.html", null ],
    [ "ImGuiDockPreviewData", "d8/d40/struct_im_gui_dock_preview_data.html", null ],
    [ "ImGuiDockRequest", "d0/dea/struct_im_gui_dock_request.html", null ],
    [ "ImGuiErrorRecoveryState", "dc/da0/struct_im_gui_error_recovery_state.html", null ],
    [ "ImGuiFocusScopeData", "d5/d65/struct_im_gui_focus_scope_data.html", null ],
    [ "ImGuiGetNameFromIndexOldToNewCallbackData", "d2/d0e/struct_im_gui_get_name_from_index_old_to_new_callback_data.html", null ],
    [ "ImGuiGroupData", "da/dc1/struct_im_gui_group_data.html", null ],
    [ "ImGuiIDStackTool", "d7/d67/struct_im_gui_i_d_stack_tool.html", null ],
    [ "ImGuiInputEvent", "d7/d1b/struct_im_gui_input_event.html", null ],
    [ "ImGuiInputEventAppFocused", "d5/dd8/struct_im_gui_input_event_app_focused.html", null ],
    [ "ImGuiInputEventKey", "db/d5c/struct_im_gui_input_event_key.html", null ],
    [ "ImGuiInputEventMouseButton", "dc/dd8/struct_im_gui_input_event_mouse_button.html", null ],
    [ "ImGuiInputEventMousePos", "d7/d2b/struct_im_gui_input_event_mouse_pos.html", null ],
    [ "ImGuiInputEventMouseViewport", "de/d82/struct_im_gui_input_event_mouse_viewport.html", null ],
    [ "ImGuiInputEventMouseWheel", "d0/d89/struct_im_gui_input_event_mouse_wheel.html", null ],
    [ "ImGuiInputEventText", "d5/dca/struct_im_gui_input_event_text.html", null ],
    [ "ImGuiInputTextCallbackData", "da/d51/struct_im_gui_input_text_callback_data.html", null ],
    [ "ImGuiInputTextDeactivatedState", "d8/db2/struct_im_gui_input_text_deactivated_state.html", null ],
    [ "ImGuiInputTextState", "da/d59/struct_im_gui_input_text_state.html", null ],
    [ "ImGuiIO", "d5/dbc/struct_im_gui_i_o.html", null ],
    [ "ImGuiKeyData", "d2/dc3/struct_im_gui_key_data.html", null ],
    [ "ImGuiKeyOwnerData", "d6/d20/struct_im_gui_key_owner_data.html", null ],
    [ "ImGuiKeyRoutingData", "dc/d72/struct_im_gui_key_routing_data.html", null ],
    [ "ImGuiKeyRoutingTable", "d6/d75/struct_im_gui_key_routing_table.html", null ],
    [ "ImGuiLastItemData", "da/d5e/struct_im_gui_last_item_data.html", null ],
    [ "ImGuiListClipper", "df/d0a/struct_im_gui_list_clipper.html", null ],
    [ "ImGuiListClipperData", "df/dfc/struct_im_gui_list_clipper_data.html", null ],
    [ "ImGuiListClipperRange", "df/d46/struct_im_gui_list_clipper_range.html", null ],
    [ "ImGuiLocEntry", "d5/dbb/struct_im_gui_loc_entry.html", null ],
    [ "ImGuiMenuColumns", "dc/d02/struct_im_gui_menu_columns.html", null ],
    [ "ImGuiMetricsConfig", "d3/d28/struct_im_gui_metrics_config.html", null ],
    [ "ImGuiMultiSelectIO", "db/de3/struct_im_gui_multi_select_i_o.html", null ],
    [ "ImGuiMultiSelectState", "dd/d6a/struct_im_gui_multi_select_state.html", null ],
    [ "ImGuiMultiSelectTempData", "d7/d5d/struct_im_gui_multi_select_temp_data.html", null ],
    [ "ImGuiNavItemData", "de/d6f/struct_im_gui_nav_item_data.html", null ],
    [ "ImGuiNextItemData", "de/d0e/struct_im_gui_next_item_data.html", null ],
    [ "ImGuiNextWindowData", "d3/dd8/struct_im_gui_next_window_data.html", null ],
    [ "ImGuiOldColumnData", "db/d99/struct_im_gui_old_column_data.html", null ],
    [ "ImGuiOldColumns", "de/ded/struct_im_gui_old_columns.html", null ],
    [ "ImGuiOnceUponAFrame", "d4/da6/struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPayload", "d7/d1d/struct_im_gui_payload.html", null ],
    [ "ImGuiPlatformImeData", "d8/dc8/struct_im_gui_platform_ime_data.html", null ],
    [ "ImGuiPlatformIO", "d0/d32/struct_im_gui_platform_i_o.html", null ],
    [ "ImGuiPlatformMonitor", "d8/d1d/struct_im_gui_platform_monitor.html", null ],
    [ "ImGuiPlotArrayGetterData", "d5/dc4/struct_im_gui_plot_array_getter_data.html", null ],
    [ "ImGuiPopupData", "da/d23/struct_im_gui_popup_data.html", null ],
    [ "ImGuiPtrOrIndex", "d7/d84/struct_im_gui_ptr_or_index.html", null ],
    [ "ImGuiResizeBorderDef", "d6/dd1/struct_im_gui_resize_border_def.html", null ],
    [ "ImGuiResizeGripDef", "d7/d0d/struct_im_gui_resize_grip_def.html", null ],
    [ "ImGuiSelectionBasicStorage", "d2/d1c/struct_im_gui_selection_basic_storage.html", [
      [ "ExampleSelectionWithDeletion", "d1/d6a/struct_example_selection_with_deletion.html", null ]
    ] ],
    [ "ImGuiSelectionExternalStorage", "d7/dac/struct_im_gui_selection_external_storage.html", null ],
    [ "ImGuiSelectionRequest", "de/d3e/struct_im_gui_selection_request.html", null ],
    [ "ImGuiSettingsHandler", "d2/d98/struct_im_gui_settings_handler.html", null ],
    [ "ImGuiShrinkWidthItem", "db/d9d/struct_im_gui_shrink_width_item.html", null ],
    [ "ImGuiSizeCallbackData", "da/d8c/struct_im_gui_size_callback_data.html", null ],
    [ "ImGuiStackLevelInfo", "da/dd0/struct_im_gui_stack_level_info.html", null ],
    [ "ImGuiStorage", "df/d15/struct_im_gui_storage.html", null ],
    [ "ImGuiStoragePair", "db/d0a/struct_im_gui_storage_pair.html", null ],
    [ "ImGuiStyle", "d7/d12/struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "d4/df8/struct_im_gui_style_mod.html", null ],
    [ "ImGuiStyleVarInfo", "db/df8/struct_im_gui_style_var_info.html", null ],
    [ "ImGuiTabBar", "d5/d7d/struct_im_gui_tab_bar.html", null ],
    [ "ImGuiTabBarSection", "dd/d2a/struct_im_gui_tab_bar_section.html", null ],
    [ "ImGuiTabItem", "d3/d39/struct_im_gui_tab_item.html", null ],
    [ "ImGuiTable", "da/d11/struct_im_gui_table.html", null ],
    [ "ImGuiTableCellData", "d4/d22/struct_im_gui_table_cell_data.html", null ],
    [ "ImGuiTableColumn", "d7/d8b/struct_im_gui_table_column.html", null ],
    [ "ImGuiTableColumnSettings", "da/daa/struct_im_gui_table_column_settings.html", null ],
    [ "ImGuiTableColumnSortSpecs", "d4/d36/struct_im_gui_table_column_sort_specs.html", null ],
    [ "ImGuiTableHeaderData", "d8/dfa/struct_im_gui_table_header_data.html", null ],
    [ "ImGuiTableInstanceData", "dc/d0a/struct_im_gui_table_instance_data.html", null ],
    [ "ImGuiTableSettings", "d2/dd0/struct_im_gui_table_settings.html", null ],
    [ "ImGuiTableSortSpecs", "d2/d81/struct_im_gui_table_sort_specs.html", null ],
    [ "ImGuiTableTempData", "d1/d09/struct_im_gui_table_temp_data.html", null ],
    [ "ImGuiTextBuffer", "da/d7d/struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextFilter", "d5/de6/struct_im_gui_text_filter.html", null ],
    [ "ImGuiTextIndex", "df/d5b/struct_im_gui_text_index.html", null ],
    [ "ImGuiTextFilter::ImGuiTextRange", "d1/dde/struct_im_gui_text_filter_1_1_im_gui_text_range.html", null ],
    [ "ImGuiTreeNodeStackData", "d0/dcb/struct_im_gui_tree_node_stack_data.html", null ],
    [ "ImGuiTypingSelectRequest", "d2/dee/struct_im_gui_typing_select_request.html", null ],
    [ "ImGuiTypingSelectState", "dd/dac/struct_im_gui_typing_select_state.html", null ],
    [ "ImGuiViewport", "d3/da6/struct_im_gui_viewport.html", [
      [ "ImGuiViewportP", "d7/dc4/struct_im_gui_viewport_p.html", null ]
    ] ],
    [ "ImGuiViewportDataMetal", "d2/db2/struct_im_gui_viewport_data_metal.html", null ],
    [ "ImGuiViewportDataOSX", "d4/d2c/struct_im_gui_viewport_data_o_s_x.html", null ],
    [ "ImGuiWindow", "d6/d8f/struct_im_gui_window.html", null ],
    [ "ImGuiWindowClass", "d4/d6c/struct_im_gui_window_class.html", null ],
    [ "ImGuiWindowDockStyle", "df/d90/struct_im_gui_window_dock_style.html", null ],
    [ "ImGuiWindowSettings", "d5/db5/struct_im_gui_window_settings.html", null ],
    [ "ImGuiWindowStackData", "d1/d7e/struct_im_gui_window_stack_data.html", null ],
    [ "ImGuiWindowTempData", "d3/d82/struct_im_gui_window_temp_data.html", null ],
    [ "ImNewWrapper", "dd/d6b/struct_im_new_wrapper.html", null ],
    [ "ImPool&lt; T &gt;", "d9/d6a/struct_im_pool.html", null ],
    [ "ImRect", "df/d8d/struct_im_rect.html", null ],
    [ "ImSpan&lt; T &gt;", "d0/dbe/struct_im_span.html", null ],
    [ "ImSpanAllocator&lt; CHUNKS &gt;", "d7/d2c/struct_im_span_allocator.html", null ],
    [ "ImTriangulator", "df/da4/struct_im_triangulator.html", null ],
    [ "ImTriangulatorNode", "d9/ddb/struct_im_triangulator_node.html", null ],
    [ "ImTriangulatorNodeSpan", "dd/dd0/struct_im_triangulator_node_span.html", null ],
    [ "ImVec1", "df/d59/struct_im_vec1.html", null ],
    [ "ImVec2", "d7/d55/struct_im_vec2.html", null ],
    [ "ImVec2ih", "d5/dc6/struct_im_vec2ih.html", null ],
    [ "ImVec4", "de/d2a/struct_im_vec4.html", null ],
    [ "ImVector&lt; T &gt;", "df/d93/struct_im_vector.html", null ],
    [ "CE::InputBuffer", "d0/d42/class_c_e_1_1_input_buffer.html", null ],
    [ "InputTextCallback_UserData", "dc/d90/struct_input_text_callback___user_data.html", null ],
    [ "CE::Motor", "d5/d72/class_c_e_1_1_motor.html", null ],
    [ "CE::MotorConfig", "d4/d9f/struct_c_e_1_1_motor_config.html", null ],
    [ "&lt;MTKViewDelegate&gt;", null, [
      [ "AppViewController()", "d9/d53/category_app_view_controller_07_08.html", null ]
    ] ],
    [ "MyDocument", "dd/d8e/struct_my_document.html", null ],
    [ "CE::Nodo&lt; T &gt;", "de/d39/class_c_e_1_1_nodo.html", null ],
    [ "&lt;NSApplicationDelegate&gt;", null, [
      [ "AppDelegate", "dd/d52/interface_app_delegate.html", null ]
    ] ],
    [ "&lt;NSCopying&gt;", null, [
      [ "FramebufferDescriptor", "d6/d1f/interface_framebuffer_descriptor.html", null ]
    ] ],
    [ "NSCursor()", "d7/dd9/category_n_s_cursor_07_08.html", null ],
    [ "NSObject", null, [
      [ "AppDelegate", "dd/d52/interface_app_delegate.html", null ],
      [ "FramebufferDescriptor", "d6/d1f/interface_framebuffer_descriptor.html", null ],
      [ "ImGuiObserver", "df/d35/interface_im_gui_observer.html", null ],
      [ "MetalBuffer", "dc/d2d/interface_metal_buffer.html", null ],
      [ "MetalContext", "d4/dae/interface_metal_context.html", null ]
    ] ],
    [ "NSOpenGLView", null, [
      [ "AppView", "de/dbd/interface_app_view.html", null ]
    ] ],
    [ "&lt;NSTextInputClient&gt;", null, [
      [ "KeyEventResponder", "d9/d62/interface_key_event_responder.html", null ]
    ] ],
    [ "NSView", null, [
      [ "KeyEventResponder", "d9/d62/interface_key_event_responder.html", null ]
    ] ],
    [ "NSWindow", null, [
      [ "ImGui_ImplOSX_Window", "dd/dab/interface_im_gui___impl_o_s_x___window.html", null ]
    ] ],
    [ "CE::Pool", "d0/d8e/class_c_e_1_1_pool.html", null ],
    [ "CE::Render", "df/d10/class_c_e_1_1_render.html", null ],
    [ "RenderResources", "d9/d42/struct_render_resources.html", null ],
    [ "ImStb::STB_TexteditState", "d3/dbb/struct_im_stb_1_1_s_t_b___textedit_state.html", null ],
    [ "STB_TexteditState", "d4/d92/struct_s_t_b___textedit_state.html", null ],
    [ "ImStb::StbFindState", "d8/dc6/struct_im_stb_1_1_stb_find_state.html", null ],
    [ "stbrp_context", "d7/dc7/structstbrp__context.html", null ],
    [ "stbrp_node", "d0/dbb/structstbrp__node.html", null ],
    [ "stbrp_rect", "d5/d50/structstbrp__rect.html", null ],
    [ "ImStb::StbTexteditRow", "db/d21/struct_im_stb_1_1_stb_textedit_row.html", null ],
    [ "StbTexteditRow", "d1/d1e/struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "d6/d7d/structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "dd/d25/structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "d9/d0c/structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "d7/d70/structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "d1/d3f/structstbtt__fontinfo.html", null ],
    [ "stbtt_kerningentry", "dc/df5/structstbtt__kerningentry.html", null ],
    [ "stbtt_pack_context", "d6/dc9/structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "d9/d46/structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "d2/d0c/structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "d4/d8d/structstbtt__vertex.html", null ],
    [ "ImStb::StbUndoRecord", "d5/d7c/struct_im_stb_1_1_stb_undo_record.html", null ],
    [ "StbUndoRecord", "d8/d4a/struct_stb_undo_record.html", null ],
    [ "ImStb::StbUndoState", "d7/da9/struct_im_stb_1_1_stb_undo_state.html", null ],
    [ "StbUndoState", "dd/dfa/struct_stb_undo_state.html", null ],
    [ "sf::Transformable", null, [
      [ "CE::Objeto", "d0/d5b/class_c_e_1_1_objeto.html", null ],
      [ "IVJ::TileMap", "dd/ddf/class_i_v_j_1_1_tile_map.html", null ]
    ] ],
    [ "&lt;UIApplicationDelegate&gt;", null, [
      [ "AppDelegate", "dd/d52/interface_app_delegate.html", null ]
    ] ],
    [ "UIResponder", null, [
      [ "AppDelegate", "dd/d52/interface_app_delegate.html", null ]
    ] ],
    [ "UIViewController", null, [
      [ "AppViewController", "db/d35/interface_app_view_controller.html", null ]
    ] ],
    [ "Uniforms", "da/d5c/struct_uniforms.html", null ],
    [ "uSynergyContext", "d8/da0/structu_synergy_context.html", null ],
    [ "uSynergyCookie", "d8/d25/structu_synergy_cookie.html", null ],
    [ "CE::Vector2D", "dc/d2a/class_c_e_1_1_vector2_d.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX10", "d0/d75/struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r___d_x10.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX11", "d8/d09/struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r___d_x11.html", null ],
    [ "VERTEX_CONSTANT_BUFFER_DX12", "d2/d16/struct_v_e_r_t_e_x___c_o_n_s_t_a_n_t___b_u_f_f_e_r___d_x12.html", null ],
    [ "WGL_WindowData", "db/d68/struct_w_g_l___window_data.html", null ]
];