var searchData=
[
  ['i_20click_20on_20it_0',['Q: Why is my widget not reacting when I click on it?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md70',1,'']]],
  ['i_20click_20on_20one_1',['Q: Why is the wrong widget reacting when I click on one?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md71',1,'']]],
  ['i_20display_20an_20image_20what_20is_20imtextureid_20how_20does_20it_20work_2',['Q: How can I display an image? What is ImTextureID, how does it work?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md77',1,'']]],
  ['i_20display_20and_20input_20non_20latin_20characters_20such_20as_20chinese_20japanese_20korean_20cyrillic_3',['Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md103',1,'']]],
  ['i_20display_20custom_20shapes_20using_20low_20level_20imdrawlist_20api_4',['Q: How can I display custom shapes? (using low-level ImDrawList API)',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md89',1,'']]],
  ['i_20easily_20use_20icons_20in_20my_20application_5',['Q: How can I easily use icons in my application?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md97',1,'']]],
  ['i_20enable_20keyboard_20or_20gamepad_20controls_6',['Q: How can I enable keyboard or gamepad controls?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md55',1,'']]],
  ['i_20get_7',['Q: Which version should I get?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md45',1,'']]],
  ['i_20handle_20dpi_20in_20my_20application_8',['I handle DPI in my application',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md132',1,'How should I handle DPI in my application?'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md93',1,'Q: How should I handle DPI in my application?']]],
  ['i_20have_20multiple_20widgets_20with_20the_20same_20label_9',['Q: How can I have multiple widgets with the same label?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md73',1,'']]],
  ['i_20have_20multiple_20windows_20with_20the_20same_20label_10',['Q: How can I have multiple windows with the same label?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md74',1,'']]],
  ['i_20have_20widgets_20with_20an_20empty_20label_11',['Q: How can I have widgets with an empty label?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md72',1,'']]],
  ['i_20help_12',['Q: How can I help?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md120',1,'']]],
  ['i_20integrated_20dear_20imgui_20in_20my_20engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_13',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md61',1,'']]],
  ['i_20integrated_20dear_20imgui_20in_20my_20engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_14',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md64',1,'']]],
  ['i_20integrated_20dear_20imgui_20in_20my_20engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_15',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md65',1,'']]],
  ['i_20interact_20with_20standard_20c_20types_20such_20as_20std_3a_3astring_20and_20std_3a_3avector_16',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md86',1,'']]],
  ['i_20load_20a_20different_20font_20than_20the_20default_17',['Q: How can I load a different font than the default?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md94',1,'']]],
  ['i_20load_20multiple_20fonts_18',['Q: How can I load multiple fonts?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md100',1,'']]],
  ['i_20move_20windows_20around_19',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md64',1,'']]],
  ['i_20tell_20whether_20to_20dispatch_20mouse_20keyboard_20to_20dear_20imgui_20or_20my_20application_20',['Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md52',1,'']]],
  ['i_20use_20maths_20operators_20with_20imvec2_21',['Q: How can I use maths operators with ImVec2?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md80',1,'']]],
  ['i_20use_20my_20own_20maths_20types_20instead_20of_20imvec2_20imvec4_22',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md83',1,'']]],
  ['i_20use_20this_20on_20a_20machine_20without_20mouse_20keyboard_20or_20screen_20input_20share_20remote_20display_23',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md58',1,'']]],
  ['iboundingbox_24',['IBoundingBox',['../d2/d22/class_c_e_1_1_i_bounding_box.html',1,'CE::IBoundingBox'],['../d2/d22/class_c_e_1_1_i_bounding_box.html#a3e214a14699a1c8eb99858449b59908b',1,'CE::IBoundingBox::IBoundingBox()']]],
  ['icomponentes_25',['IComponentes',['../db/d58/class_c_e_1_1_i_componentes.html',1,'CE']]],
  ['icon_20fonts_26',['ICON FONTS',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md174',1,'']]],
  ['icon_20fonts_27',['Using Icon Fonts',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md144',1,'']]],
  ['icons_28',['Using Custom Colorful Icons',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md156',1,'']]],
  ['icons_20in_20my_20application_29',['Q: How can I easily use icons in my application?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md97',1,'']]],
  ['icontrol_30',['IControl',['../dd/d1b/class_c_e_1_1_i_control.html',1,'CE::IControl'],['../dd/d1b/class_c_e_1_1_i_control.html#a11fbfdb4a8a5b8661acb8fa5971d1626',1,'CE::IControl::IControl()']]],
  ['id_20stack_20system_31',['Q: About the ID Stack system...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md69',1,'']]],
  ['id_5fcurva_32',['id_curva',['../da/d77/class_c_e_1_1_i_paths.html#a9b1dfa8095cc502dc173b0151093586a',1,'CE::IPaths']]],
  ['ide_33',['IDE',['../dir_8b68a0713bfda8cb2375ff7049bc9ecd.html#autotoc_md201',1,'Windows with Visual Studio&apos;s IDE'],['../dir_4f636e46b298919a819a900db95bee8e.html#autotoc_md208',1,'Windows with Visual Studio&apos;s IDE']]],
  ['idialogo_34',['IDialogo',['../d0/d10/class_i_v_j_1_1_i_dialogo.html',1,'IVJ']]],
  ['iindicador_35',['IIndicador',['../da/d14/class_i_v_j_1_1_i_indicador.html',1,'IVJ']]],
  ['iinteractuable_36',['IInteractuable',['../d6/db0/class_i_v_j_1_1_i_interactuable.html',1,'IVJ']]],
  ['iiterador_37',['IIterador',['../df/d28/class_c_e_1_1_i_iterador.html',1,'CE']]],
  ['iiterador_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20niveles_20_3e_20_3e_38',['IIterador&lt; std::pair&lt; std::string, Niveles &gt; &gt;',['../df/d28/class_c_e_1_1_i_iterador.html',1,'CE']]],
  ['image_20what_20is_20imtextureid_20how_20does_20it_20work_39',['Q: How can I display an image? What is ImTextureID, how does it work?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md77',1,'']]],
  ['imanipulardatos_40',['IManipularDatos',['../de/d1b/class_c_e_1_1_i_manipular_datos.html',1,'CE']]],
  ['imanipulardatos_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20niveles_20_3e_20_3e_41',['IManipularDatos&lt; std::pair&lt; std::string, Niveles &gt; &gt;',['../de/d1b/class_c_e_1_1_i_manipular_datos.html',1,'CE']]],
  ['imaquinaestado_42',['IMaquinaEstado',['../d9/d98/class_i_v_j_1_1_i_maquina_estado.html',1,'IVJ']]],
  ['imbitarray_43',['ImBitArray',['../d6/d40/struct_im_bit_array.html',1,'']]],
  ['imbitarray_3c_20imguikey_5fnamedkey_5fcount_2c_20_2dimguikey_5fnamedkey_5fbegin_20_3e_44',['ImBitArray&lt; ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN &gt;',['../d6/d40/struct_im_bit_array.html',1,'']]],
  ['imbitvector_45',['ImBitVector',['../d6/d28/struct_im_bit_vector.html',1,'']]],
  ['imchunkstream_46',['ImChunkStream',['../d0/d05/struct_im_chunk_stream.html',1,'']]],
  ['imchunkstream_3c_20imguitablesettings_20_3e_47',['ImChunkStream&lt; ImGuiTableSettings &gt;',['../d0/d05/struct_im_chunk_stream.html',1,'']]],
  ['imchunkstream_3c_20imguiwindowsettings_20_3e_48',['ImChunkStream&lt; ImGuiWindowSettings &gt;',['../d0/d05/struct_im_chunk_stream.html',1,'']]],
  ['imcolor_49',['ImColor',['../db/da3/struct_im_color.html',1,'']]],
  ['imdrawchannel_50',['ImDrawChannel',['../df/d94/struct_im_draw_channel.html',1,'']]],
  ['imdrawcmd_51',['ImDrawCmd',['../d6/d65/struct_im_draw_cmd.html',1,'']]],
  ['imdrawcmdheader_52',['ImDrawCmdHeader',['../d0/de9/struct_im_draw_cmd_header.html',1,'']]],
  ['imdrawdata_53',['ImDrawData',['../d9/d78/struct_im_draw_data.html',1,'']]],
  ['imdrawdatabuilder_54',['ImDrawDataBuilder',['../de/d11/struct_im_draw_data_builder.html',1,'']]],
  ['imdrawlist_55',['ImDrawList',['../dd/d30/struct_im_draw_list.html',1,'']]],
  ['imdrawlist_20api_56',['Q: How can I display custom shapes? (using low-level ImDrawList API)',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md89',1,'']]],
  ['imdrawlistshareddata_57',['ImDrawListSharedData',['../dd/d70/struct_im_draw_list_shared_data.html',1,'']]],
  ['imdrawlistsplitter_58',['ImDrawListSplitter',['../d4/de1/struct_im_draw_list_splitter.html',1,'']]],
  ['imdrawvert_59',['ImDrawVert',['../dc/d86/struct_im_draw_vert.html',1,'']]],
  ['imdrawvertallegro_60',['ImDrawVertAllegro',['../db/dae/struct_im_draw_vert_allegro.html',1,'']]],
  ['imfont_61',['ImFont',['../d7/dc9/struct_im_font.html',1,'']]],
  ['imfontatlas_62',['ImFontAtlas',['../d5/d9e/struct_im_font_atlas.html',1,'']]],
  ['imfontatlascustomrect_63',['ImFontAtlasCustomRect',['../d1/d27/struct_im_font_atlas_custom_rect.html',1,'']]],
  ['imfontbuilddstdata_64',['ImFontBuildDstData',['../d4/d3b/struct_im_font_build_dst_data.html',1,'']]],
  ['imfontbuilddstdataft_65',['ImFontBuildDstDataFT',['../d0/deb/struct_im_font_build_dst_data_f_t.html',1,'']]],
  ['imfontbuilderio_66',['ImFontBuilderIO',['../d3/d0e/struct_im_font_builder_i_o.html',1,'']]],
  ['imfontbuildsrcdata_67',['ImFontBuildSrcData',['../d0/d98/struct_im_font_build_src_data.html',1,'']]],
  ['imfontbuildsrcdataft_68',['ImFontBuildSrcDataFT',['../dd/dff/struct_im_font_build_src_data_f_t.html',1,'']]],
  ['imfontbuildsrcglyphft_69',['ImFontBuildSrcGlyphFT',['../db/d4e/struct_im_font_build_src_glyph_f_t.html',1,'']]],
  ['imfontconfig_70',['ImFontConfig',['../d5/d84/struct_im_font_config.html',1,'']]],
  ['imfontglyph_71',['ImFontGlyph',['../df/d57/struct_im_font_glyph.html',1,'']]],
  ['imfontglyphrangesbuilder_72',['ImFontGlyphRangesBuilder',['../d4/d56/struct_im_font_glyph_ranges_builder.html',1,'']]],
  ['imgl3wprocs_73',['ImGL3WProcs',['../d4/d6c/union_im_g_l3_w_procs.html',1,'']]],
  ['imgui_74',['ImGui',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md110',1,'Q: Can you create elaborate/serious tools with Dear ImGui?'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md113',1,'Q: Can you reskin the look of Dear ImGui?'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md107',1,'Q: Who uses Dear ImGui?']]],
  ['imgui_20in_20my_20engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_75',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md61',1,'']]],
  ['imgui_20in_20my_20engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_76',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md64',1,'']]],
  ['imgui_20in_20my_20engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_77',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md65',1,'']]],
  ['imgui_20or_20my_20application_78',['Q: How can I tell whether to dispatch mouse/keyboard to Dear ImGui or my application?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md52',1,'']]],
  ['imgui_20overloads_20new_20widgets_79',['SFML related ImGui overloads / new widgets',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md11',1,'']]],
  ['imgui_20sfml_20in_20your_20code_80',['Using ImGui-SFML in your code',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md7',1,'']]],
  ['imgui_3a_20backends_81',['Dear ImGui: Backends',['../d7/dcc/md_build_2__deps_2imgui-src_2docs_2_b_a_c_k_e_n_d_s.html#autotoc_md17',1,'']]],
  ['imgui_3a_20examples_82',['Dear ImGui: Examples',['../d3/d03/md_build_2__deps_2imgui-src_2docs_2_e_x_a_m_p_l_e_s.html#autotoc_md32',1,'']]],
  ['imgui_3a_20using_20fonts_83',['Dear ImGui: Using Fonts',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md122',1,'']]],
  ['imgui_5ffreetype_84',['imgui_freetype',['../dir_86f64a97f091f3ad21a621c3d810792e.html#autotoc_md213',1,'imgui_freetype'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md147',1,'Using FreeType Rasterizer (imgui_freetype)']]],
  ['imgui_5fimplallegro5_5fdata_85',['ImGui_ImplAllegro5_Data',['../d4/d33/struct_im_gui___impl_allegro5___data.html',1,'']]],
  ['imgui_5fimpldx10_5fdata_86',['ImGui_ImplDX10_Data',['../dd/d9e/struct_im_gui___impl_d_x10___data.html',1,'']]],
  ['imgui_5fimpldx10_5frenderstate_87',['ImGui_ImplDX10_RenderState',['../d4/d80/struct_im_gui___impl_d_x10___render_state.html',1,'']]],
  ['imgui_5fimpldx10_5fviewportdata_88',['ImGui_ImplDX10_ViewportData',['../db/dfc/struct_im_gui___impl_d_x10___viewport_data.html',1,'']]],
  ['imgui_5fimpldx11_5fdata_89',['ImGui_ImplDX11_Data',['../d1/d6d/struct_im_gui___impl_d_x11___data.html',1,'']]],
  ['imgui_5fimpldx11_5frenderstate_90',['ImGui_ImplDX11_RenderState',['../db/dbf/struct_im_gui___impl_d_x11___render_state.html',1,'']]],
  ['imgui_5fimpldx11_5fviewportdata_91',['ImGui_ImplDX11_ViewportData',['../d9/d2c/struct_im_gui___impl_d_x11___viewport_data.html',1,'']]],
  ['imgui_5fimpldx12_5fdata_92',['ImGui_ImplDX12_Data',['../d3/dcd/struct_im_gui___impl_d_x12___data.html',1,'']]],
  ['imgui_5fimpldx12_5fframecontext_93',['ImGui_ImplDX12_FrameContext',['../dd/d05/struct_im_gui___impl_d_x12___frame_context.html',1,'']]],
  ['imgui_5fimpldx12_5finitinfo_94',['ImGui_ImplDX12_InitInfo',['../d0/df5/struct_im_gui___impl_d_x12___init_info.html',1,'']]],
  ['imgui_5fimpldx12_5frenderbuffers_95',['ImGui_ImplDX12_RenderBuffers',['../d4/dc1/struct_im_gui___impl_d_x12___render_buffers.html',1,'']]],
  ['imgui_5fimpldx12_5frenderstate_96',['ImGui_ImplDX12_RenderState',['../d3/db6/struct_im_gui___impl_d_x12___render_state.html',1,'']]],
  ['imgui_5fimpldx12_5ftexture_97',['ImGui_ImplDX12_Texture',['../dc/d64/struct_im_gui___impl_d_x12___texture.html',1,'']]],
  ['imgui_5fimpldx12_5fviewportdata_98',['ImGui_ImplDX12_ViewportData',['../d5/d89/struct_im_gui___impl_d_x12___viewport_data.html',1,'']]],
  ['imgui_5fimpldx9_5fdata_99',['ImGui_ImplDX9_Data',['../db/d07/struct_im_gui___impl_d_x9___data.html',1,'']]],
  ['imgui_5fimpldx9_5fviewportdata_100',['ImGui_ImplDX9_ViewportData',['../d5/d9e/struct_im_gui___impl_d_x9___viewport_data.html',1,'']]],
  ['imgui_5fimplglfw_5fdata_101',['ImGui_ImplGlfw_Data',['../d5/d6e/struct_im_gui___impl_glfw___data.html',1,'']]],
  ['imgui_5fimplglfw_5fviewportdata_102',['ImGui_ImplGlfw_ViewportData',['../d2/d04/struct_im_gui___impl_glfw___viewport_data.html',1,'']]],
  ['imgui_5fimplmetal_5fdata_103',['ImGui_ImplMetal_Data',['../d0/dda/struct_im_gui___impl_metal___data.html',1,'']]],
  ['imgui_5fimplopengl2_5fdata_104',['ImGui_ImplOpenGL2_Data',['../d5/d7a/struct_im_gui___impl_open_g_l2___data.html',1,'']]],
  ['imgui_5fimplopengl3_5fdata_105',['ImGui_ImplOpenGL3_Data',['../dc/d45/struct_im_gui___impl_open_g_l3___data.html',1,'']]],
  ['imgui_5fimplosx_5fdata_106',['ImGui_ImplOSX_Data',['../d2/d61/struct_im_gui___impl_o_s_x___data.html',1,'']]],
  ['imgui_5fimplosx_5fwindow_107',['ImGui_ImplOSX_Window',['../dd/dab/interface_im_gui___impl_o_s_x___window.html',1,'']]],
  ['imgui_5fimplsdl2_5fdata_108',['ImGui_ImplSDL2_Data',['../de/d4e/struct_im_gui___impl_s_d_l2___data.html',1,'']]],
  ['imgui_5fimplsdl2_5fviewportdata_109',['ImGui_ImplSDL2_ViewportData',['../d3/de7/struct_im_gui___impl_s_d_l2___viewport_data.html',1,'']]],
  ['imgui_5fimplsdl3_5fdata_110',['ImGui_ImplSDL3_Data',['../dc/de5/struct_im_gui___impl_s_d_l3___data.html',1,'']]],
  ['imgui_5fimplsdl3_5fviewportdata_111',['ImGui_ImplSDL3_ViewportData',['../d9/dc3/struct_im_gui___impl_s_d_l3___viewport_data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fdata_112',['ImGui_ImplSDLGPU3_Data',['../d7/dfe/struct_im_gui___impl_s_d_l_g_p_u3___data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fframedata_113',['ImGui_ImplSDLGPU3_FrameData',['../d7/de3/struct_im_gui___impl_s_d_l_g_p_u3___frame_data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5finitinfo_114',['ImGui_ImplSDLGPU3_InitInfo',['../d8/d4e/struct_im_gui___impl_s_d_l_g_p_u3___init_info.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5fdata_115',['ImGui_ImplSDLRenderer2_Data',['../d1/d05/struct_im_gui___impl_s_d_l_renderer2___data.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5frenderstate_116',['ImGui_ImplSDLRenderer2_RenderState',['../da/d7d/struct_im_gui___impl_s_d_l_renderer2___render_state.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5fdata_117',['ImGui_ImplSDLRenderer3_Data',['../df/d54/struct_im_gui___impl_s_d_l_renderer3___data.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5frenderstate_118',['ImGui_ImplSDLRenderer3_RenderState',['../d0/d19/struct_im_gui___impl_s_d_l_renderer3___render_state.html',1,'']]],
  ['imgui_5fimplvulkan_5fdata_119',['ImGui_ImplVulkan_Data',['../d2/d86/struct_im_gui___impl_vulkan___data.html',1,'']]],
  ['imgui_5fimplvulkan_5fframerenderbuffers_120',['ImGui_ImplVulkan_FrameRenderBuffers',['../d4/d27/struct_im_gui___impl_vulkan___frame_render_buffers.html',1,'']]],
  ['imgui_5fimplvulkan_5finitinfo_121',['ImGui_ImplVulkan_InitInfo',['../de/d2c/struct_im_gui___impl_vulkan___init_info.html',1,'']]],
  ['imgui_5fimplvulkan_5frenderstate_122',['ImGui_ImplVulkan_RenderState',['../d6/db6/struct_im_gui___impl_vulkan___render_state.html',1,'']]],
  ['imgui_5fimplvulkan_5ftexture_123',['ImGui_ImplVulkan_Texture',['../da/db3/struct_im_gui___impl_vulkan___texture.html',1,'']]],
  ['imgui_5fimplvulkan_5fviewportdata_124',['ImGui_ImplVulkan_ViewportData',['../d1/dca/struct_im_gui___impl_vulkan___viewport_data.html',1,'']]],
  ['imgui_5fimplvulkan_5fwindowrenderbuffers_125',['ImGui_ImplVulkan_WindowRenderBuffers',['../d4/d6d/struct_im_gui___impl_vulkan___window_render_buffers.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframe_126',['ImGui_ImplVulkanH_Frame',['../d6/df7/struct_im_gui___impl_vulkan_h___frame.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframesemaphores_127',['ImGui_ImplVulkanH_FrameSemaphores',['../d5/d82/struct_im_gui___impl_vulkan_h___frame_semaphores.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindow_128',['ImGui_ImplVulkanH_Window',['../de/d27/struct_im_gui___impl_vulkan_h___window.html',1,'']]],
  ['imgui_5fimplwgpu_5fdata_129',['ImGui_ImplWGPU_Data',['../df/d96/struct_im_gui___impl_w_g_p_u___data.html',1,'']]],
  ['imgui_5fimplwgpu_5finitinfo_130',['ImGui_ImplWGPU_InitInfo',['../dd/d00/struct_im_gui___impl_w_g_p_u___init_info.html',1,'']]],
  ['imgui_5fimplwgpu_5frenderstate_131',['ImGui_ImplWGPU_RenderState',['../da/d0a/struct_im_gui___impl_w_g_p_u___render_state.html',1,'']]],
  ['imgui_5fimplwin32_5fdata_132',['ImGui_ImplWin32_Data',['../d5/d71/struct_im_gui___impl_win32___data.html',1,'']]],
  ['imgui_5fimplwin32_5fviewportdata_133',['ImGui_ImplWin32_ViewportData',['../d5/d40/struct_im_gui___impl_win32___viewport_data.html',1,'']]],
  ['imguiboxselectstate_134',['ImGuiBoxSelectState',['../dd/d35/struct_im_gui_box_select_state.html',1,'']]],
  ['imguicolormod_135',['ImGuiColorMod',['../da/d8e/struct_im_gui_color_mod.html',1,'']]],
  ['imguicombopreviewdata_136',['ImGuiComboPreviewData',['../d7/d3a/struct_im_gui_combo_preview_data.html',1,'']]],
  ['imguicontext_137',['ImGuiContext',['../d7/da3/struct_im_gui_context.html',1,'']]],
  ['imguicontexthook_138',['ImGuiContextHook',['../df/dbc/struct_im_gui_context_hook.html',1,'']]],
  ['imguidatatypeinfo_139',['ImGuiDataTypeInfo',['../d5/dbe/struct_im_gui_data_type_info.html',1,'']]],
  ['imguidatatypestorage_140',['ImGuiDataTypeStorage',['../de/d93/struct_im_gui_data_type_storage.html',1,'']]],
  ['imguideactivateditemdata_141',['ImGuiDeactivatedItemData',['../de/d87/struct_im_gui_deactivated_item_data.html',1,'']]],
  ['imguidebugallocentry_142',['ImGuiDebugAllocEntry',['../dd/d28/struct_im_gui_debug_alloc_entry.html',1,'']]],
  ['imguidebugallocinfo_143',['ImGuiDebugAllocInfo',['../d2/d45/struct_im_gui_debug_alloc_info.html',1,'']]],
  ['imguidemowindowdata_144',['ImGuiDemoWindowData',['../dc/d71/struct_im_gui_demo_window_data.html',1,'']]],
  ['imguidockcontext_145',['ImGuiDockContext',['../d1/dcf/struct_im_gui_dock_context.html',1,'']]],
  ['imguidockcontextprunenodedata_146',['ImGuiDockContextPruneNodeData',['../de/db6/struct_im_gui_dock_context_prune_node_data.html',1,'']]],
  ['imguidocknode_147',['ImGuiDockNode',['../dd/dcf/struct_im_gui_dock_node.html',1,'']]],
  ['imguidocknodesettings_148',['ImGuiDockNodeSettings',['../d2/d29/struct_im_gui_dock_node_settings.html',1,'']]],
  ['imguidocknodetreeinfo_149',['ImGuiDockNodeTreeInfo',['../df/dca/struct_im_gui_dock_node_tree_info.html',1,'']]],
  ['imguidockpreviewdata_150',['ImGuiDockPreviewData',['../d8/d40/struct_im_gui_dock_preview_data.html',1,'']]],
  ['imguidockrequest_151',['ImGuiDockRequest',['../d0/dea/struct_im_gui_dock_request.html',1,'']]],
  ['imguierrorrecoverystate_152',['ImGuiErrorRecoveryState',['../dc/da0/struct_im_gui_error_recovery_state.html',1,'']]],
  ['imguifocusscopedata_153',['ImGuiFocusScopeData',['../d5/d65/struct_im_gui_focus_scope_data.html',1,'']]],
  ['imguigetnamefromindexoldtonewcallbackdata_154',['ImGuiGetNameFromIndexOldToNewCallbackData',['../d2/d0e/struct_im_gui_get_name_from_index_old_to_new_callback_data.html',1,'']]],
  ['imguigroupdata_155',['ImGuiGroupData',['../da/dc1/struct_im_gui_group_data.html',1,'']]],
  ['imguiidstacktool_156',['ImGuiIDStackTool',['../d7/d67/struct_im_gui_i_d_stack_tool.html',1,'']]],
  ['imguiinputevent_157',['ImGuiInputEvent',['../d7/d1b/struct_im_gui_input_event.html',1,'']]],
  ['imguiinputeventappfocused_158',['ImGuiInputEventAppFocused',['../d5/dd8/struct_im_gui_input_event_app_focused.html',1,'']]],
  ['imguiinputeventkey_159',['ImGuiInputEventKey',['../db/d5c/struct_im_gui_input_event_key.html',1,'']]],
  ['imguiinputeventmousebutton_160',['ImGuiInputEventMouseButton',['../dc/dd8/struct_im_gui_input_event_mouse_button.html',1,'']]],
  ['imguiinputeventmousepos_161',['ImGuiInputEventMousePos',['../d7/d2b/struct_im_gui_input_event_mouse_pos.html',1,'']]],
  ['imguiinputeventmouseviewport_162',['ImGuiInputEventMouseViewport',['../de/d82/struct_im_gui_input_event_mouse_viewport.html',1,'']]],
  ['imguiinputeventmousewheel_163',['ImGuiInputEventMouseWheel',['../d0/d89/struct_im_gui_input_event_mouse_wheel.html',1,'']]],
  ['imguiinputeventtext_164',['ImGuiInputEventText',['../d5/dca/struct_im_gui_input_event_text.html',1,'']]],
  ['imguiinputtextcallbackdata_165',['ImGuiInputTextCallbackData',['../da/d51/struct_im_gui_input_text_callback_data.html',1,'']]],
  ['imguiinputtextdeactivatedstate_166',['ImGuiInputTextDeactivatedState',['../d8/db2/struct_im_gui_input_text_deactivated_state.html',1,'']]],
  ['imguiinputtextstate_167',['ImGuiInputTextState',['../da/d59/struct_im_gui_input_text_state.html',1,'']]],
  ['imguiio_168',['ImGuiIO',['../d5/dbc/struct_im_gui_i_o.html',1,'']]],
  ['imguikeydata_169',['ImGuiKeyData',['../d2/dc3/struct_im_gui_key_data.html',1,'']]],
  ['imguikeyownerdata_170',['ImGuiKeyOwnerData',['../d6/d20/struct_im_gui_key_owner_data.html',1,'']]],
  ['imguikeyroutingdata_171',['ImGuiKeyRoutingData',['../dc/d72/struct_im_gui_key_routing_data.html',1,'']]],
  ['imguikeyroutingtable_172',['ImGuiKeyRoutingTable',['../d6/d75/struct_im_gui_key_routing_table.html',1,'']]],
  ['imguilastitemdata_173',['ImGuiLastItemData',['../da/d5e/struct_im_gui_last_item_data.html',1,'']]],
  ['imguilistclipper_174',['ImGuiListClipper',['../df/d0a/struct_im_gui_list_clipper.html',1,'']]],
  ['imguilistclipperdata_175',['ImGuiListClipperData',['../df/dfc/struct_im_gui_list_clipper_data.html',1,'']]],
  ['imguilistclipperrange_176',['ImGuiListClipperRange',['../df/d46/struct_im_gui_list_clipper_range.html',1,'']]],
  ['imguilocentry_177',['ImGuiLocEntry',['../d5/dbb/struct_im_gui_loc_entry.html',1,'']]],
  ['imguimenucolumns_178',['ImGuiMenuColumns',['../dc/d02/struct_im_gui_menu_columns.html',1,'']]],
  ['imguimetricsconfig_179',['ImGuiMetricsConfig',['../d3/d28/struct_im_gui_metrics_config.html',1,'']]],
  ['imguimultiselectio_180',['ImGuiMultiSelectIO',['../db/de3/struct_im_gui_multi_select_i_o.html',1,'']]],
  ['imguimultiselectstate_181',['ImGuiMultiSelectState',['../dd/d6a/struct_im_gui_multi_select_state.html',1,'']]],
  ['imguimultiselecttempdata_182',['ImGuiMultiSelectTempData',['../d7/d5d/struct_im_gui_multi_select_temp_data.html',1,'']]],
  ['imguinavitemdata_183',['ImGuiNavItemData',['../de/d6f/struct_im_gui_nav_item_data.html',1,'']]],
  ['imguinextitemdata_184',['ImGuiNextItemData',['../de/d0e/struct_im_gui_next_item_data.html',1,'']]],
  ['imguinextwindowdata_185',['ImGuiNextWindowData',['../d3/dd8/struct_im_gui_next_window_data.html',1,'']]],
  ['imguiobserver_186',['ImGuiObserver',['../df/d35/interface_im_gui_observer.html',1,'']]],
  ['imguioldcolumndata_187',['ImGuiOldColumnData',['../db/d99/struct_im_gui_old_column_data.html',1,'']]],
  ['imguioldcolumns_188',['ImGuiOldColumns',['../de/ded/struct_im_gui_old_columns.html',1,'']]],
  ['imguionceuponaframe_189',['ImGuiOnceUponAFrame',['../d4/da6/struct_im_gui_once_upon_a_frame.html',1,'']]],
  ['imguipayload_190',['ImGuiPayload',['../d7/d1d/struct_im_gui_payload.html',1,'']]],
  ['imguiplatformimedata_191',['ImGuiPlatformImeData',['../d8/dc8/struct_im_gui_platform_ime_data.html',1,'']]],
  ['imguiplatformio_192',['ImGuiPlatformIO',['../d0/d32/struct_im_gui_platform_i_o.html',1,'']]],
  ['imguiplatformmonitor_193',['ImGuiPlatformMonitor',['../d8/d1d/struct_im_gui_platform_monitor.html',1,'']]],
  ['imguiplotarraygetterdata_194',['ImGuiPlotArrayGetterData',['../d5/dc4/struct_im_gui_plot_array_getter_data.html',1,'']]],
  ['imguipopupdata_195',['ImGuiPopupData',['../da/d23/struct_im_gui_popup_data.html',1,'']]],
  ['imguiptrorindex_196',['ImGuiPtrOrIndex',['../d7/d84/struct_im_gui_ptr_or_index.html',1,'']]],
  ['imguiresizeborderdef_197',['ImGuiResizeBorderDef',['../d6/dd1/struct_im_gui_resize_border_def.html',1,'']]],
  ['imguiresizegripdef_198',['ImGuiResizeGripDef',['../d7/d0d/struct_im_gui_resize_grip_def.html',1,'']]],
  ['imguiselectionbasicstorage_199',['ImGuiSelectionBasicStorage',['../d2/d1c/struct_im_gui_selection_basic_storage.html',1,'']]],
  ['imguiselectionexternalstorage_200',['ImGuiSelectionExternalStorage',['../d7/dac/struct_im_gui_selection_external_storage.html',1,'']]],
  ['imguiselectionrequest_201',['ImGuiSelectionRequest',['../de/d3e/struct_im_gui_selection_request.html',1,'']]],
  ['imguisettingshandler_202',['ImGuiSettingsHandler',['../d2/d98/struct_im_gui_settings_handler.html',1,'']]],
  ['imguishrinkwidthitem_203',['ImGuiShrinkWidthItem',['../db/d9d/struct_im_gui_shrink_width_item.html',1,'']]],
  ['imguisizecallbackdata_204',['ImGuiSizeCallbackData',['../da/d8c/struct_im_gui_size_callback_data.html',1,'']]],
  ['imguistacklevelinfo_205',['ImGuiStackLevelInfo',['../da/dd0/struct_im_gui_stack_level_info.html',1,'']]],
  ['imguistorage_206',['ImGuiStorage',['../df/d15/struct_im_gui_storage.html',1,'']]],
  ['imguistoragepair_207',['ImGuiStoragePair',['../db/d0a/struct_im_gui_storage_pair.html',1,'']]],
  ['imguistyle_208',['ImGuiStyle',['../d7/d12/struct_im_gui_style.html',1,'']]],
  ['imguistylemod_209',['ImGuiStyleMod',['../d4/df8/struct_im_gui_style_mod.html',1,'']]],
  ['imguistylevarinfo_210',['ImGuiStyleVarInfo',['../db/df8/struct_im_gui_style_var_info.html',1,'']]],
  ['imguitabbar_211',['ImGuiTabBar',['../d5/d7d/struct_im_gui_tab_bar.html',1,'']]],
  ['imguitabbarsection_212',['ImGuiTabBarSection',['../dd/d2a/struct_im_gui_tab_bar_section.html',1,'']]],
  ['imguitabitem_213',['ImGuiTabItem',['../d3/d39/struct_im_gui_tab_item.html',1,'']]],
  ['imguitable_214',['ImGuiTable',['../da/d11/struct_im_gui_table.html',1,'']]],
  ['imguitablecelldata_215',['ImGuiTableCellData',['../d4/d22/struct_im_gui_table_cell_data.html',1,'']]],
  ['imguitablecolumn_216',['ImGuiTableColumn',['../d7/d8b/struct_im_gui_table_column.html',1,'']]],
  ['imguitablecolumnsettings_217',['ImGuiTableColumnSettings',['../da/daa/struct_im_gui_table_column_settings.html',1,'']]],
  ['imguitablecolumnsortspecs_218',['ImGuiTableColumnSortSpecs',['../d4/d36/struct_im_gui_table_column_sort_specs.html',1,'']]],
  ['imguitableheaderdata_219',['ImGuiTableHeaderData',['../d8/dfa/struct_im_gui_table_header_data.html',1,'']]],
  ['imguitableinstancedata_220',['ImGuiTableInstanceData',['../dc/d0a/struct_im_gui_table_instance_data.html',1,'']]],
  ['imguitablesettings_221',['ImGuiTableSettings',['../d2/dd0/struct_im_gui_table_settings.html',1,'']]],
  ['imguitablesortspecs_222',['ImGuiTableSortSpecs',['../d2/d81/struct_im_gui_table_sort_specs.html',1,'']]],
  ['imguitabletempdata_223',['ImGuiTableTempData',['../d1/d09/struct_im_gui_table_temp_data.html',1,'']]],
  ['imguitextbuffer_224',['ImGuiTextBuffer',['../da/d7d/struct_im_gui_text_buffer.html',1,'']]],
  ['imguitextfilter_225',['ImGuiTextFilter',['../d5/de6/struct_im_gui_text_filter.html',1,'']]],
  ['imguitextindex_226',['ImGuiTextIndex',['../df/d5b/struct_im_gui_text_index.html',1,'']]],
  ['imguitextrange_227',['ImGuiTextRange',['../d1/dde/struct_im_gui_text_filter_1_1_im_gui_text_range.html',1,'ImGuiTextFilter']]],
  ['imguitreenodestackdata_228',['ImGuiTreeNodeStackData',['../d0/dcb/struct_im_gui_tree_node_stack_data.html',1,'']]],
  ['imguitypingselectrequest_229',['ImGuiTypingSelectRequest',['../d2/dee/struct_im_gui_typing_select_request.html',1,'']]],
  ['imguitypingselectstate_230',['ImGuiTypingSelectState',['../dd/dac/struct_im_gui_typing_select_state.html',1,'']]],
  ['imguiviewport_231',['ImGuiViewport',['../d3/da6/struct_im_gui_viewport.html',1,'']]],
  ['imguiviewportdatametal_232',['ImGuiViewportDataMetal',['../d2/db2/struct_im_gui_viewport_data_metal.html',1,'']]],
  ['imguiviewportdataosx_233',['ImGuiViewportDataOSX',['../d4/d2c/struct_im_gui_viewport_data_o_s_x.html',1,'']]],
  ['imguiviewportp_234',['ImGuiViewportP',['../d7/dc4/struct_im_gui_viewport_p.html',1,'']]],
  ['imguiwindow_235',['ImGuiWindow',['../d6/d8f/struct_im_gui_window.html',1,'']]],
  ['imguiwindowclass_236',['ImGuiWindowClass',['../d4/d6c/struct_im_gui_window_class.html',1,'']]],
  ['imguiwindowdockstyle_237',['ImGuiWindowDockStyle',['../df/d90/struct_im_gui_window_dock_style.html',1,'']]],
  ['imguiwindowsettings_238',['ImGuiWindowSettings',['../d5/db5/struct_im_gui_window_settings.html',1,'']]],
  ['imguiwindowstackdata_239',['ImGuiWindowStackData',['../d1/d7e/struct_im_gui_window_stack_data.html',1,'']]],
  ['imguiwindowtempdata_240',['ImGuiWindowTempData',['../d3/d82/struct_im_gui_window_temp_data.html',1,'']]],
  ['imnewwrapper_241',['ImNewWrapper',['../dd/d6b/struct_im_new_wrapper.html',1,'']]],
  ['impool_242',['ImPool',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['impool_3c_20imguimultiselectstate_20_3e_243',['ImPool&lt; ImGuiMultiSelectState &gt;',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_244',['ImPool&lt; ImGuiTabBar &gt;',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitable_20_3e_245',['ImPool&lt; ImGuiTable &gt;',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['imrect_246',['ImRect',['../df/d8d/struct_im_rect.html',1,'']]],
  ['imspan_247',['ImSpan',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecelldata_20_3e_248',['ImSpan&lt; ImGuiTableCellData &gt;',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecolumn_20_3e_249',['ImSpan&lt; ImGuiTableColumn &gt;',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecolumnidx_20_3e_250',['ImSpan&lt; ImGuiTableColumnIdx &gt;',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspanallocator_251',['ImSpanAllocator',['../d7/d2c/struct_im_span_allocator.html',1,'']]],
  ['imtextureid_20how_20does_20it_20work_252',['Q: How can I display an image? What is ImTextureID, how does it work?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md77',1,'']]],
  ['imtriangulator_253',['ImTriangulator',['../df/da4/struct_im_triangulator.html',1,'']]],
  ['imtriangulatornode_254',['ImTriangulatorNode',['../d9/ddb/struct_im_triangulator_node.html',1,'']]],
  ['imtriangulatornodespan_255',['ImTriangulatorNodeSpan',['../dd/dd0/struct_im_triangulator_node_span.html',1,'']]],
  ['imvec1_256',['ImVec1',['../df/d59/struct_im_vec1.html',1,'']]],
  ['imvec2_257',['ImVec2',['../d7/d55/struct_im_vec2.html',1,'ImVec2'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md80',1,'Q: How can I use maths operators with ImVec2?']]],
  ['imvec2_20imvec4_258',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md83',1,'']]],
  ['imvec2ih_259',['ImVec2ih',['../d5/dc6/struct_im_vec2ih.html',1,'']]],
  ['imvec4_260',['ImVec4',['../de/d2a/struct_im_vec4.html',1,'ImVec4'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md83',1,'Q: How can I use my own maths types instead of ImVec2/ImVec4?']]],
  ['imvector_261',['ImVector',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_262',['ImVector&lt; char * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_3e_263',['ImVector&lt; char &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_264',['ImVector&lt; const char * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20dxgi_5fswap_5fchain_5fdesc_20_3e_265',['ImVector&lt; DXGI_SWAP_CHAIN_DESC &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20exampleasset_20_3e_266',['ImVector&lt; ExampleAsset &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20exampletreenode_20_2a_20_3e_267',['ImVector&lt; ExampleTreeNode * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20float_20_3e_268',['ImVector&lt; float &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_269',['ImVector&lt; ImDrawChannel &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_270',['ImVector&lt; ImDrawCmd &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_271',['ImVector&lt; ImDrawIdx &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_272',['ImVector&lt; ImDrawList * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_273',['ImVector&lt; ImDrawVert &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvertallegro_20_3e_274',['ImVector&lt; ImDrawVertAllegro &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_275',['ImVector&lt; ImFont * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontatlascustomrect_20_3e_276',['ImVector&lt; ImFontAtlasCustomRect &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontbuildsrcglyphft_20_3e_277',['ImVector&lt; ImFontBuildSrcGlyphFT &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_278',['ImVector&lt; ImFontConfig &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_279',['ImVector&lt; ImFontGlyph &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkan_5fframerenderbuffers_20_3e_280',['ImVector&lt; ImGui_ImplVulkan_FrameRenderBuffers &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframe_20_3e_281',['ImVector&lt; ImGui_ImplVulkanH_Frame &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframesemaphores_20_3e_282',['ImVector&lt; ImGui_ImplVulkanH_FrameSemaphores &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_283',['ImVector&lt; ImGuiColorMod &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicontexthook_20_3e_284',['ImVector&lt; ImGuiContextHook &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguidocknodesettings_20_3e_285',['ImVector&lt; ImGuiDockNodeSettings &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguidockrequest_20_3e_286',['ImVector&lt; ImGuiDockRequest &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguifocusscopedata_20_3e_287',['ImVector&lt; ImGuiFocusScopeData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_288',['ImVector&lt; ImGuiGroupData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_289',['ImVector&lt; ImGuiID &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiinputevent_20_3e_290',['ImVector&lt; ImGuiInputEvent &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_291',['ImVector&lt; ImGuiItemFlags &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguikeyroutingdata_20_3e_292',['ImVector&lt; ImGuiKeyRoutingData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguilistclipperdata_20_3e_293',['ImVector&lt; ImGuiListClipperData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguilistclipperrange_20_3e_294',['ImVector&lt; ImGuiListClipperRange &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguimultiselectstate_20_3e_295',['ImVector&lt; ImGuiMultiSelectState &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguimultiselecttempdata_20_3e_296',['ImVector&lt; ImGuiMultiSelectTempData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguioldcolumndata_20_3e_297',['ImVector&lt; ImGuiOldColumnData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguioldcolumns_20_3e_298',['ImVector&lt; ImGuiOldColumns &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiplatformmonitor_20_3e_299',['ImVector&lt; ImGuiPlatformMonitor &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_300',['ImVector&lt; ImGuiPopupData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_301',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiselectionrequest_20_3e_302',['ImVector&lt; ImGuiSelectionRequest &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_303',['ImVector&lt; ImGuiSettingsHandler &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_304',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistacklevelinfo_20_3e_305',['ImVector&lt; ImGuiStackLevelInfo &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistoragepair_20_3e_306',['ImVector&lt; ImGuiStoragePair &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_307',['ImVector&lt; ImGuiStyleMod &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_308',['ImVector&lt; ImGuiTabBar &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_309',['ImVector&lt; ImGuiTabItem &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitable_20_3e_310',['ImVector&lt; ImGuiTable &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitablecolumnsortspecs_20_3e_311',['ImVector&lt; ImGuiTableColumnSortSpecs &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitableheaderdata_20_3e_312',['ImVector&lt; ImGuiTableHeaderData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitableinstancedata_20_3e_313',['ImVector&lt; ImGuiTableInstanceData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabletempdata_20_3e_314',['ImVector&lt; ImGuiTableTempData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_315',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitreenodestackdata_20_3e_316',['ImVector&lt; ImGuiTreeNodeStackData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiviewport_20_2a_20_3e_317',['ImVector&lt; ImGuiViewport * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiviewportp_20_2a_20_3e_318',['ImVector&lt; ImGuiViewportP * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_319',['ImVector&lt; ImGuiWindow * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindowstackdata_20_3e_320',['ImVector&lt; ImGuiWindowStackData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e_321',['ImVector&lt; ImTextureID &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu16_20_3e_322',['ImVector&lt; ImU16 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_323',['ImVector&lt; ImU32 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu8_20_3e_324',['ImVector&lt; ImU8 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_325',['ImVector&lt; ImVec2 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_326',['ImVector&lt; ImVec4 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_327',['ImVector&lt; ImWchar &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20int_20_3e_328',['ImVector&lt; int &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20mydocument_20_2a_20_3e_329',['ImVector&lt; MyDocument * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_330',['ImVector&lt; MyDocument &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20sdl_5ffcolor_20_3e_331',['ImVector&lt; SDL_FColor &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamecontroller_20_2a_20_3e_332',['ImVector&lt; SDL_GameController * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamepad_20_2a_20_3e_333',['ImVector&lt; SDL_Gamepad * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_334',['ImVector&lt; unsigned char &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['in_20my_20application_335',['in my application',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md132',1,'How should I handle DPI in my application?'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md97',1,'Q: How can I easily use icons in my application?'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md93',1,'Q: How should I handle DPI in my application?']]],
  ['in_20my_20engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_336',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md61',1,'']]],
  ['in_20my_20engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_337',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md64',1,'']]],
  ['in_20my_20engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_338',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md65',1,'']]],
  ['in_20repository_339',['Credits/Licenses For Fonts Included In Repository',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md171',1,'']]],
  ['in_20source_20code_340',['Loading Font Data Embedded In Source Code',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md141',1,'']]],
  ['in_20your_20code_341',['Using ImGui-SFML in your code',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md7',1,'']]],
  ['included_20in_20repository_342',['Credits/Licenses For Fonts Included In Repository',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md171',1,'']]],
  ['index_343',['Index',['../d6/d2e/md_build_2__deps_2imgui-src_2docs_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md26',1,'Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md37',1,'Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md123',1,'Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md40',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md43',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md46',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md50',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md53',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md56',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md59',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md62',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md66',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md75',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md78',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md81',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md84',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md87',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md90',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md95',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md98',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md101',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md104',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md108',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md111',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md114',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md117',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md121',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md130',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md133',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md136',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md139',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md142',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md145',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md148',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md151',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md154',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md158',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md161',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md164',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md169',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md172',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md177',1,'Return to IndexReturn to Index']]],
  ['index_20return_20to_20index_344',['Index Return to Index',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md40',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md43',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md46',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md50',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md53',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md56',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md59',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md62',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md66',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md75',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md78',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md81',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md84',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md87',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md90',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md95',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md98',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md101',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md104',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md108',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md111',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md114',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md117',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md121',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md130',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md133',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md136',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md139',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md142',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md145',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md148',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md151',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md154',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md158',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md161',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md164',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md169',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md172',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md177',1,'Return to IndexReturn to Index']]],
  ['index_20return_20to_20index_20return_20to_20index_345',['index Return to Index Return to Index',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md40',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md43',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md46',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md50',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md53',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md56',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md59',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md62',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md66',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md75',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md78',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md81',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md84',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md87',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md90',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md95',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md98',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md101',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md104',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md108',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md111',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md114',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md117',1,'Return to IndexReturn to Index'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md121',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md130',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md133',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md136',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md139',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md142',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md145',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md148',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md151',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md154',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md158',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md161',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md164',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md169',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md172',1,'Return to IndexReturn to Index'],['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md177',1,'Return to IndexReturn to Index']]],
  ['initialization_20version_20and_20error_20reference_346',['Initialization, version and error reference',['../d9/d54/group__init.html',1,'']]],
  ['inombre_347',['INombre',['../d2/d35/class_c_e_1_1_i_nombre.html',1,'CE::INombre'],['../d2/d35/class_c_e_1_1_i_nombre.html#a40616df04c9af2f5ead403d8034f22a7',1,'CE::INombre::INombre()']]],
  ['input_20non_20latin_20characters_20such_20as_20chinese_20japanese_20korean_20cyrillic_348',['Q: How can I display and input non-Latin characters such as Chinese, Japanese, Korean, Cyrillic?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md103',1,'']]],
  ['input_20reference_349',['Input reference',['../dc/df1/group__input.html',1,'']]],
  ['input_20share_20remote_20display_350',['Q: How can I use this on a machine without mouse, keyboard or screen? (input share, remote display)',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md58',1,'']]],
  ['inputbuffer_351',['InputBuffer',['../d0/d42/class_c_e_1_1_input_buffer.html',1,'CE::InputBuffer'],['../d0/d42/class_c_e_1_1_input_buffer.html#a359e1b03010be1f0b7e98961f605bc12',1,'CE::InputBuffer::InputBuffer()']]],
  ['inputtextcallback_5fuserdata_352',['InputTextCallback_UserData',['../dc/d90/struct_input_text_callback___user_data.html',1,'']]],
  ['instead_20of_20imvec2_20imvec4_353',['Q: How can I use my own maths types instead of ImVec2/ImVec4?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md83',1,'']]],
  ['instead_20of_20text_354',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md61',1,'']]],
  ['instructions_355',['Fonts Loading Instructions',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md135',1,'']]],
  ['integrated_20dear_20imgui_20in_20my_20engine_20and_20little_20squares_20are_20showing_20instead_20of_20text_356',['Q: I integrated Dear ImGui in my engine and little squares are showing instead of text...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md61',1,'']]],
  ['integrated_20dear_20imgui_20in_20my_20engine_20and_20some_20elements_20are_20clipping_20or_20disappearing_20when_20i_20move_20windows_20around_357',['Q: I integrated Dear ImGui in my engine and some elements are clipping or disappearing when I move windows around...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md64',1,'']]],
  ['integrated_20dear_20imgui_20in_20my_20engine_20and_20some_20elements_20are_20displaying_20outside_20their_20expected_20windows_20boundaries_358',['Q: I integrated Dear ImGui in my engine and some elements are displaying outside their expected windows boundaries...',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md65',1,'']]],
  ['integrating_20backends_359',['Integrating backends',['../d7/dcc/md_build_2__deps_2imgui-src_2docs_2_b_a_c_k_e_n_d_s.html#autotoc_md18',1,'']]],
  ['integrating_20into_20your_20cmake_20project_360',['Building and integrating into your CMake project',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md4',1,'']]],
  ['integrating_20into_20your_20project_20manually_361',['Integrating into your project manually',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md5',1,'']]],
  ['integration_362',['Integration',['../dir_b5fd01b70b8887ff731c5516bbbda194.html#autotoc_md184',1,'Getting Started &amp;amp; Integration'],['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md48',1,'Q&amp;amp;A: Integration']]],
  ['interact_20with_20standard_20c_20types_20such_20as_20std_3a_3astring_20and_20std_3a_3avector_363',['Q: How can I interact with standard C++ types (such as std::string and std::vector)?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md86',1,'']]],
  ['into_20your_20cmake_20project_364',['Building and integrating into your CMake project',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md4',1,'']]],
  ['into_20your_20project_20manually_365',['Integrating into your project manually',['../dir_45359432c8268bf56bca676685b35f56.html#autotoc_md5',1,'']]],
  ['introduction_366',['Introduction',['../dir_56baed6dcab2f0da4ebff02bd05bccdb.html#autotoc_md196',1,'']]],
  ['invalid_20filename_20due_20to_20use_20of_20or_20unexpected_20working_20directory_367',['(1) Invalid filename due to use of &lt;span class=&quot;tt&quot;&gt;\\&lt;/span&gt; or unexpected working directory.',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md126',1,'']]],
  ['invalid_20utf_208_20encoding_20of_20your_20non_20ascii_20strings_368',['(2) Invalid UTF-8 encoding of your non-ASCII strings.',['../dd/d57/md_build_2__deps_2imgui-src_2docs_2_f_o_n_t_s.html#autotoc_md127',1,'']]],
  ['ios_20osx_20metal_20example_369',['iOS / OSX Metal example',['../dir_56baed6dcab2f0da4ebff02bd05bccdb.html#autotoc_md195',1,'']]],
  ['ipaths_370',['IPaths',['../da/d77/class_c_e_1_1_i_paths.html',1,'CE::IPaths'],['../da/d77/class_c_e_1_1_i_paths.html#acfd49ca856c5bc05e07f35ec73899236',1,'CE::IPaths::IPaths()']]],
  ['irayo_371',['IRayo',['../d1/db4/class_i_v_j_1_1_i_rayo.html',1,'IVJ']]],
  ['irespawn_372',['IRespawn',['../da/d77/class_c_e_1_1_i_respawn.html',1,'CE::IRespawn'],['../da/d77/class_c_e_1_1_i_respawn.html#add0aa0e333e6f9ee9f656fe97db04a04',1,'CE::IRespawn::IRespawn(std::vector&lt; std::shared_ptr&lt; IComponentes &gt; &gt; &amp;lista_comp, int max)'],['../da/d77/class_c_e_1_1_i_respawn.html#a223240d8c2a8d109d26d68afc51666eb',1,'CE::IRespawn::IRespawn(int max, int w, int h, IVJ::Entidad *pre)']]],
  ['is_20imtextureid_20how_20does_20it_20work_373',['Q: How can I display an image? What is ImTextureID, how does it work?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md77',1,'']]],
  ['is_20my_20widget_20not_20reacting_20when_20i_20click_20on_20it_374',['Q: Why is my widget not reacting when I click on it?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md70',1,'']]],
  ['is_20the_20documentation_375',['Q: Where is the documentation?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md39',1,'']]],
  ['is_20the_20wrong_20widget_20reacting_20when_20i_20click_20on_20one_376',['Q: Why is the wrong widget reacting when I click on one?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md71',1,'']]],
  ['is_20this_20library_20called_377',['Q. What is this library called?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md42',1,'']]],
  ['isactivo_378',['isActivo',['../dd/d1b/class_c_e_1_1_i_control.html#a11745dfe5d742f6f4811fcce7d799c9e',1,'CE::IControl']]],
  ['ishader_379',['IShader',['../d4/d4c/class_c_e_1_1_i_shader.html',1,'CE::IShader'],['../d4/d4c/class_c_e_1_1_i_shader.html#a7518b1b84278bcb26a5e84b2c25e373c',1,'CE::IShader::IShader()']]],
  ['isprite_380',['ISprite',['../da/d2f/class_c_e_1_1_i_sprite.html',1,'CE::ISprite'],['../da/d2f/class_c_e_1_1_i_sprite.html#a12190145f66e32198a59a09980bcf291',1,'CE::ISprite::ISprite(const sf::Texture &amp;textura, float escala)'],['../da/d2f/class_c_e_1_1_i_sprite.html#a8f31af8225612effa7c430b77b9a370f',1,'CE::ISprite::ISprite(const sf::Texture &amp;textura, int w, int h, float escala)']]],
  ['issue_381',['How to open an issue',['../d6/d2e/md_build_2__deps_2imgui-src_2docs_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md29',1,'']]],
  ['issues_382',['Known issues',['../dir_86f64a97f091f3ad21a621c3d810792e.html#autotoc_md217',1,'']]],
  ['issues_20vs_20discussions_383',['&apos;Issues&apos; vs &apos;Discussions&apos;',['../d6/d2e/md_build_2__deps_2imgui-src_2docs_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md28',1,'']]],
  ['istats_384',['IStats',['../d8/dde/class_c_e_1_1_i_stats.html',1,'CE']]],
  ['it_385',['Q: Why is my widget not reacting when I click on it?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md70',1,'']]],
  ['it_20work_386',['Q: How can I display an image? What is ImTextureID, how does it work?',['../d5/d26/md_build_2__deps_2imgui-src_2docs_2_f_a_q.html#autotoc_md77',1,'']]],
  ['it_20works_387',['How it works',['../dir_b5fd01b70b8887ff731c5516bbbda194.html#autotoc_md181',1,'']]],
  ['iteractual_388',['iterActual',['../df/d28/class_c_e_1_1_i_iterador.html#a03626272fab97999cd038e693a3085ca',1,'CE::IIterador::iterActual()'],['../d7/d15/class_c_e_1_1_lista.html#ab6a3f1e76103704afe86365acfefbaea',1,'CE::Lista::iterActual()']]],
  ['iterfinal_389',['iterFinal',['../df/d28/class_c_e_1_1_i_iterador.html#aa5d764da7b0c7538f37c41c6eb675612',1,'CE::IIterador::iterFinal()'],['../d7/d15/class_c_e_1_1_lista.html#a3779e4ab20f27a2308bdcdc70ecc1329',1,'CE::Lista::iterFinal()']]],
  ['iterinicio_390',['iterInicio',['../df/d28/class_c_e_1_1_i_iterador.html#a688fd4df583c36dd1fdb9a5ffe030ed5',1,'CE::IIterador::iterInicio()'],['../d7/d15/class_c_e_1_1_lista.html#acb0443735ba1ee5906a75e719de75b19',1,'CE::Lista::iterInicio()']]],
  ['itersiguiente_391',['iterSiguiente',['../df/d28/class_c_e_1_1_i_iterador.html#a7aff9318dd7b0bcc27112fd7bd21f224',1,'CE::IIterador::iterSiguiente()'],['../d7/d15/class_c_e_1_1_lista.html#a93d3b09cba613b737ce7eac43729ab0b',1,'CE::Lista::iterSiguiente()']]],
  ['itertermino_392',['iterTermino',['../df/d28/class_c_e_1_1_i_iterador.html#a10d95ddf7c07185feb11bf452986a781',1,'CE::IIterador::iterTermino()'],['../d7/d15/class_c_e_1_1_lista.html#aaf4202f53ec896644f7bbe4b876acef6',1,'CE::Lista::iterTermino()']]],
  ['itexto_393',['ITexto',['../d4/d25/class_c_e_1_1_i_texto.html',1,'CE::ITexto'],['../d4/d25/class_c_e_1_1_i_texto.html#a8b39a373bd37c5c8efd488d17e8a8137',1,'CE::ITexto::ITexto()']]],
  ['itimer_394',['ITimer',['../d9/d72/class_c_e_1_1_i_timer.html',1,'CE::ITimer'],['../d9/d72/class_c_e_1_1_i_timer.html#a88495293c8b661b95eb780735bc59920',1,'CE::ITimer::ITimer()']]],
  ['itransform_395',['ITransform',['../d5/d49/class_c_e_1_1_i_transform.html',1,'CE::ITransform'],['../d5/d49/class_c_e_1_1_i_transform.html#a30b75c66342b9ad6a2bc77342e260e8d',1,'CE::ITransform::ITransform()'],['../d5/d49/class_c_e_1_1_i_transform.html#a18568cb7af4a0098d66d4de376bba019',1,'CE::ITransform::ITransform(const Vector2D &amp;pos, const Vector2D &amp;vel, float ang)']]],
  ['itriangulo_396',['ITriangulo',['../d5/d95/class_i_v_j_1_1_i_triangulo.html',1,'IVJ']]],
  ['izq_397',['izq',['../dd/d1b/class_c_e_1_1_i_control.html#aab921fcbbdcc945b9f875b48f268c424',1,'CE::IControl']]]
];
