var searchData=
[
  ['iboundingbox_0',['IBoundingBox',['../d2/d22/class_c_e_1_1_i_bounding_box.html',1,'CE']]],
  ['icomponentes_1',['IComponentes',['../db/d58/class_c_e_1_1_i_componentes.html',1,'CE']]],
  ['icontrol_2',['IControl',['../dd/d1b/class_c_e_1_1_i_control.html',1,'CE']]],
  ['idialogo_3',['IDialogo',['../d0/d10/class_i_v_j_1_1_i_dialogo.html',1,'IVJ']]],
  ['iindicador_4',['IIndicador',['../da/d14/class_i_v_j_1_1_i_indicador.html',1,'IVJ']]],
  ['iinteractuable_5',['IInteractuable',['../d6/db0/class_i_v_j_1_1_i_interactuable.html',1,'IVJ']]],
  ['iiterador_6',['IIterador',['../df/d28/class_c_e_1_1_i_iterador.html',1,'CE']]],
  ['iiterador_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20niveles_20_3e_20_3e_7',['IIterador&lt; std::pair&lt; std::string, Niveles &gt; &gt;',['../df/d28/class_c_e_1_1_i_iterador.html',1,'CE']]],
  ['imanipulardatos_8',['IManipularDatos',['../de/d1b/class_c_e_1_1_i_manipular_datos.html',1,'CE']]],
  ['imanipulardatos_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20niveles_20_3e_20_3e_9',['IManipularDatos&lt; std::pair&lt; std::string, Niveles &gt; &gt;',['../de/d1b/class_c_e_1_1_i_manipular_datos.html',1,'CE']]],
  ['imaquinaestado_10',['IMaquinaEstado',['../d9/d98/class_i_v_j_1_1_i_maquina_estado.html',1,'IVJ']]],
  ['imbitarray_11',['ImBitArray',['../d6/d40/struct_im_bit_array.html',1,'']]],
  ['imbitarray_3c_20imguikey_5fnamedkey_5fcount_2c_20_2dimguikey_5fnamedkey_5fbegin_20_3e_12',['ImBitArray&lt; ImGuiKey_NamedKey_COUNT, -ImGuiKey_NamedKey_BEGIN &gt;',['../d6/d40/struct_im_bit_array.html',1,'']]],
  ['imbitvector_13',['ImBitVector',['../d6/d28/struct_im_bit_vector.html',1,'']]],
  ['imchunkstream_14',['ImChunkStream',['../d0/d05/struct_im_chunk_stream.html',1,'']]],
  ['imchunkstream_3c_20imguitablesettings_20_3e_15',['ImChunkStream&lt; ImGuiTableSettings &gt;',['../d0/d05/struct_im_chunk_stream.html',1,'']]],
  ['imchunkstream_3c_20imguiwindowsettings_20_3e_16',['ImChunkStream&lt; ImGuiWindowSettings &gt;',['../d0/d05/struct_im_chunk_stream.html',1,'']]],
  ['imcolor_17',['ImColor',['../db/da3/struct_im_color.html',1,'']]],
  ['imdrawchannel_18',['ImDrawChannel',['../df/d94/struct_im_draw_channel.html',1,'']]],
  ['imdrawcmd_19',['ImDrawCmd',['../d6/d65/struct_im_draw_cmd.html',1,'']]],
  ['imdrawcmdheader_20',['ImDrawCmdHeader',['../d0/de9/struct_im_draw_cmd_header.html',1,'']]],
  ['imdrawdata_21',['ImDrawData',['../d9/d78/struct_im_draw_data.html',1,'']]],
  ['imdrawdatabuilder_22',['ImDrawDataBuilder',['../de/d11/struct_im_draw_data_builder.html',1,'']]],
  ['imdrawlist_23',['ImDrawList',['../dd/d30/struct_im_draw_list.html',1,'']]],
  ['imdrawlistshareddata_24',['ImDrawListSharedData',['../dd/d70/struct_im_draw_list_shared_data.html',1,'']]],
  ['imdrawlistsplitter_25',['ImDrawListSplitter',['../d4/de1/struct_im_draw_list_splitter.html',1,'']]],
  ['imdrawvert_26',['ImDrawVert',['../dc/d86/struct_im_draw_vert.html',1,'']]],
  ['imdrawvertallegro_27',['ImDrawVertAllegro',['../db/dae/struct_im_draw_vert_allegro.html',1,'']]],
  ['imfont_28',['ImFont',['../d7/dc9/struct_im_font.html',1,'']]],
  ['imfontatlas_29',['ImFontAtlas',['../d5/d9e/struct_im_font_atlas.html',1,'']]],
  ['imfontatlascustomrect_30',['ImFontAtlasCustomRect',['../d1/d27/struct_im_font_atlas_custom_rect.html',1,'']]],
  ['imfontbuilddstdata_31',['ImFontBuildDstData',['../d4/d3b/struct_im_font_build_dst_data.html',1,'']]],
  ['imfontbuilddstdataft_32',['ImFontBuildDstDataFT',['../d0/deb/struct_im_font_build_dst_data_f_t.html',1,'']]],
  ['imfontbuilderio_33',['ImFontBuilderIO',['../d3/d0e/struct_im_font_builder_i_o.html',1,'']]],
  ['imfontbuildsrcdata_34',['ImFontBuildSrcData',['../d0/d98/struct_im_font_build_src_data.html',1,'']]],
  ['imfontbuildsrcdataft_35',['ImFontBuildSrcDataFT',['../dd/dff/struct_im_font_build_src_data_f_t.html',1,'']]],
  ['imfontbuildsrcglyphft_36',['ImFontBuildSrcGlyphFT',['../db/d4e/struct_im_font_build_src_glyph_f_t.html',1,'']]],
  ['imfontconfig_37',['ImFontConfig',['../d5/d84/struct_im_font_config.html',1,'']]],
  ['imfontglyph_38',['ImFontGlyph',['../df/d57/struct_im_font_glyph.html',1,'']]],
  ['imfontglyphrangesbuilder_39',['ImFontGlyphRangesBuilder',['../d4/d56/struct_im_font_glyph_ranges_builder.html',1,'']]],
  ['imgl3wprocs_40',['ImGL3WProcs',['../d4/d6c/union_im_g_l3_w_procs.html',1,'']]],
  ['imgui_5fimplallegro5_5fdata_41',['ImGui_ImplAllegro5_Data',['../d4/d33/struct_im_gui___impl_allegro5___data.html',1,'']]],
  ['imgui_5fimpldx10_5fdata_42',['ImGui_ImplDX10_Data',['../dd/d9e/struct_im_gui___impl_d_x10___data.html',1,'']]],
  ['imgui_5fimpldx10_5frenderstate_43',['ImGui_ImplDX10_RenderState',['../d4/d80/struct_im_gui___impl_d_x10___render_state.html',1,'']]],
  ['imgui_5fimpldx10_5fviewportdata_44',['ImGui_ImplDX10_ViewportData',['../db/dfc/struct_im_gui___impl_d_x10___viewport_data.html',1,'']]],
  ['imgui_5fimpldx11_5fdata_45',['ImGui_ImplDX11_Data',['../d1/d6d/struct_im_gui___impl_d_x11___data.html',1,'']]],
  ['imgui_5fimpldx11_5frenderstate_46',['ImGui_ImplDX11_RenderState',['../db/dbf/struct_im_gui___impl_d_x11___render_state.html',1,'']]],
  ['imgui_5fimpldx11_5fviewportdata_47',['ImGui_ImplDX11_ViewportData',['../d9/d2c/struct_im_gui___impl_d_x11___viewport_data.html',1,'']]],
  ['imgui_5fimpldx12_5fdata_48',['ImGui_ImplDX12_Data',['../d3/dcd/struct_im_gui___impl_d_x12___data.html',1,'']]],
  ['imgui_5fimpldx12_5fframecontext_49',['ImGui_ImplDX12_FrameContext',['../dd/d05/struct_im_gui___impl_d_x12___frame_context.html',1,'']]],
  ['imgui_5fimpldx12_5finitinfo_50',['ImGui_ImplDX12_InitInfo',['../d0/df5/struct_im_gui___impl_d_x12___init_info.html',1,'']]],
  ['imgui_5fimpldx12_5frenderbuffers_51',['ImGui_ImplDX12_RenderBuffers',['../d4/dc1/struct_im_gui___impl_d_x12___render_buffers.html',1,'']]],
  ['imgui_5fimpldx12_5frenderstate_52',['ImGui_ImplDX12_RenderState',['../d3/db6/struct_im_gui___impl_d_x12___render_state.html',1,'']]],
  ['imgui_5fimpldx12_5ftexture_53',['ImGui_ImplDX12_Texture',['../dc/d64/struct_im_gui___impl_d_x12___texture.html',1,'']]],
  ['imgui_5fimpldx12_5fviewportdata_54',['ImGui_ImplDX12_ViewportData',['../d5/d89/struct_im_gui___impl_d_x12___viewport_data.html',1,'']]],
  ['imgui_5fimpldx9_5fdata_55',['ImGui_ImplDX9_Data',['../db/d07/struct_im_gui___impl_d_x9___data.html',1,'']]],
  ['imgui_5fimpldx9_5fviewportdata_56',['ImGui_ImplDX9_ViewportData',['../d5/d9e/struct_im_gui___impl_d_x9___viewport_data.html',1,'']]],
  ['imgui_5fimplglfw_5fdata_57',['ImGui_ImplGlfw_Data',['../d5/d6e/struct_im_gui___impl_glfw___data.html',1,'']]],
  ['imgui_5fimplglfw_5fviewportdata_58',['ImGui_ImplGlfw_ViewportData',['../d2/d04/struct_im_gui___impl_glfw___viewport_data.html',1,'']]],
  ['imgui_5fimplmetal_5fdata_59',['ImGui_ImplMetal_Data',['../d0/dda/struct_im_gui___impl_metal___data.html',1,'']]],
  ['imgui_5fimplopengl2_5fdata_60',['ImGui_ImplOpenGL2_Data',['../d5/d7a/struct_im_gui___impl_open_g_l2___data.html',1,'']]],
  ['imgui_5fimplopengl3_5fdata_61',['ImGui_ImplOpenGL3_Data',['../dc/d45/struct_im_gui___impl_open_g_l3___data.html',1,'']]],
  ['imgui_5fimplosx_5fdata_62',['ImGui_ImplOSX_Data',['../d2/d61/struct_im_gui___impl_o_s_x___data.html',1,'']]],
  ['imgui_5fimplosx_5fwindow_63',['ImGui_ImplOSX_Window',['../dd/dab/interface_im_gui___impl_o_s_x___window.html',1,'']]],
  ['imgui_5fimplsdl2_5fdata_64',['ImGui_ImplSDL2_Data',['../de/d4e/struct_im_gui___impl_s_d_l2___data.html',1,'']]],
  ['imgui_5fimplsdl2_5fviewportdata_65',['ImGui_ImplSDL2_ViewportData',['../d3/de7/struct_im_gui___impl_s_d_l2___viewport_data.html',1,'']]],
  ['imgui_5fimplsdl3_5fdata_66',['ImGui_ImplSDL3_Data',['../dc/de5/struct_im_gui___impl_s_d_l3___data.html',1,'']]],
  ['imgui_5fimplsdl3_5fviewportdata_67',['ImGui_ImplSDL3_ViewportData',['../d9/dc3/struct_im_gui___impl_s_d_l3___viewport_data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fdata_68',['ImGui_ImplSDLGPU3_Data',['../d7/dfe/struct_im_gui___impl_s_d_l_g_p_u3___data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5fframedata_69',['ImGui_ImplSDLGPU3_FrameData',['../d7/de3/struct_im_gui___impl_s_d_l_g_p_u3___frame_data.html',1,'']]],
  ['imgui_5fimplsdlgpu3_5finitinfo_70',['ImGui_ImplSDLGPU3_InitInfo',['../d8/d4e/struct_im_gui___impl_s_d_l_g_p_u3___init_info.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5fdata_71',['ImGui_ImplSDLRenderer2_Data',['../d1/d05/struct_im_gui___impl_s_d_l_renderer2___data.html',1,'']]],
  ['imgui_5fimplsdlrenderer2_5frenderstate_72',['ImGui_ImplSDLRenderer2_RenderState',['../da/d7d/struct_im_gui___impl_s_d_l_renderer2___render_state.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5fdata_73',['ImGui_ImplSDLRenderer3_Data',['../df/d54/struct_im_gui___impl_s_d_l_renderer3___data.html',1,'']]],
  ['imgui_5fimplsdlrenderer3_5frenderstate_74',['ImGui_ImplSDLRenderer3_RenderState',['../d0/d19/struct_im_gui___impl_s_d_l_renderer3___render_state.html',1,'']]],
  ['imgui_5fimplvulkan_5fdata_75',['ImGui_ImplVulkan_Data',['../d2/d86/struct_im_gui___impl_vulkan___data.html',1,'']]],
  ['imgui_5fimplvulkan_5fframerenderbuffers_76',['ImGui_ImplVulkan_FrameRenderBuffers',['../d4/d27/struct_im_gui___impl_vulkan___frame_render_buffers.html',1,'']]],
  ['imgui_5fimplvulkan_5finitinfo_77',['ImGui_ImplVulkan_InitInfo',['../de/d2c/struct_im_gui___impl_vulkan___init_info.html',1,'']]],
  ['imgui_5fimplvulkan_5frenderstate_78',['ImGui_ImplVulkan_RenderState',['../d6/db6/struct_im_gui___impl_vulkan___render_state.html',1,'']]],
  ['imgui_5fimplvulkan_5ftexture_79',['ImGui_ImplVulkan_Texture',['../da/db3/struct_im_gui___impl_vulkan___texture.html',1,'']]],
  ['imgui_5fimplvulkan_5fviewportdata_80',['ImGui_ImplVulkan_ViewportData',['../d1/dca/struct_im_gui___impl_vulkan___viewport_data.html',1,'']]],
  ['imgui_5fimplvulkan_5fwindowrenderbuffers_81',['ImGui_ImplVulkan_WindowRenderBuffers',['../d4/d6d/struct_im_gui___impl_vulkan___window_render_buffers.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframe_82',['ImGui_ImplVulkanH_Frame',['../d6/df7/struct_im_gui___impl_vulkan_h___frame.html',1,'']]],
  ['imgui_5fimplvulkanh_5fframesemaphores_83',['ImGui_ImplVulkanH_FrameSemaphores',['../d5/d82/struct_im_gui___impl_vulkan_h___frame_semaphores.html',1,'']]],
  ['imgui_5fimplvulkanh_5fwindow_84',['ImGui_ImplVulkanH_Window',['../de/d27/struct_im_gui___impl_vulkan_h___window.html',1,'']]],
  ['imgui_5fimplwgpu_5fdata_85',['ImGui_ImplWGPU_Data',['../df/d96/struct_im_gui___impl_w_g_p_u___data.html',1,'']]],
  ['imgui_5fimplwgpu_5finitinfo_86',['ImGui_ImplWGPU_InitInfo',['../dd/d00/struct_im_gui___impl_w_g_p_u___init_info.html',1,'']]],
  ['imgui_5fimplwgpu_5frenderstate_87',['ImGui_ImplWGPU_RenderState',['../da/d0a/struct_im_gui___impl_w_g_p_u___render_state.html',1,'']]],
  ['imgui_5fimplwin32_5fdata_88',['ImGui_ImplWin32_Data',['../d5/d71/struct_im_gui___impl_win32___data.html',1,'']]],
  ['imgui_5fimplwin32_5fviewportdata_89',['ImGui_ImplWin32_ViewportData',['../d5/d40/struct_im_gui___impl_win32___viewport_data.html',1,'']]],
  ['imguiboxselectstate_90',['ImGuiBoxSelectState',['../dd/d35/struct_im_gui_box_select_state.html',1,'']]],
  ['imguicolormod_91',['ImGuiColorMod',['../da/d8e/struct_im_gui_color_mod.html',1,'']]],
  ['imguicombopreviewdata_92',['ImGuiComboPreviewData',['../d7/d3a/struct_im_gui_combo_preview_data.html',1,'']]],
  ['imguicontext_93',['ImGuiContext',['../d7/da3/struct_im_gui_context.html',1,'']]],
  ['imguicontexthook_94',['ImGuiContextHook',['../df/dbc/struct_im_gui_context_hook.html',1,'']]],
  ['imguidatatypeinfo_95',['ImGuiDataTypeInfo',['../d5/dbe/struct_im_gui_data_type_info.html',1,'']]],
  ['imguidatatypestorage_96',['ImGuiDataTypeStorage',['../de/d93/struct_im_gui_data_type_storage.html',1,'']]],
  ['imguideactivateditemdata_97',['ImGuiDeactivatedItemData',['../de/d87/struct_im_gui_deactivated_item_data.html',1,'']]],
  ['imguidebugallocentry_98',['ImGuiDebugAllocEntry',['../dd/d28/struct_im_gui_debug_alloc_entry.html',1,'']]],
  ['imguidebugallocinfo_99',['ImGuiDebugAllocInfo',['../d2/d45/struct_im_gui_debug_alloc_info.html',1,'']]],
  ['imguidemowindowdata_100',['ImGuiDemoWindowData',['../dc/d71/struct_im_gui_demo_window_data.html',1,'']]],
  ['imguidockcontext_101',['ImGuiDockContext',['../d1/dcf/struct_im_gui_dock_context.html',1,'']]],
  ['imguidockcontextprunenodedata_102',['ImGuiDockContextPruneNodeData',['../de/db6/struct_im_gui_dock_context_prune_node_data.html',1,'']]],
  ['imguidocknode_103',['ImGuiDockNode',['../dd/dcf/struct_im_gui_dock_node.html',1,'']]],
  ['imguidocknodesettings_104',['ImGuiDockNodeSettings',['../d2/d29/struct_im_gui_dock_node_settings.html',1,'']]],
  ['imguidocknodetreeinfo_105',['ImGuiDockNodeTreeInfo',['../df/dca/struct_im_gui_dock_node_tree_info.html',1,'']]],
  ['imguidockpreviewdata_106',['ImGuiDockPreviewData',['../d8/d40/struct_im_gui_dock_preview_data.html',1,'']]],
  ['imguidockrequest_107',['ImGuiDockRequest',['../d0/dea/struct_im_gui_dock_request.html',1,'']]],
  ['imguierrorrecoverystate_108',['ImGuiErrorRecoveryState',['../dc/da0/struct_im_gui_error_recovery_state.html',1,'']]],
  ['imguifocusscopedata_109',['ImGuiFocusScopeData',['../d5/d65/struct_im_gui_focus_scope_data.html',1,'']]],
  ['imguigetnamefromindexoldtonewcallbackdata_110',['ImGuiGetNameFromIndexOldToNewCallbackData',['../d2/d0e/struct_im_gui_get_name_from_index_old_to_new_callback_data.html',1,'']]],
  ['imguigroupdata_111',['ImGuiGroupData',['../da/dc1/struct_im_gui_group_data.html',1,'']]],
  ['imguiidstacktool_112',['ImGuiIDStackTool',['../d7/d67/struct_im_gui_i_d_stack_tool.html',1,'']]],
  ['imguiinputevent_113',['ImGuiInputEvent',['../d7/d1b/struct_im_gui_input_event.html',1,'']]],
  ['imguiinputeventappfocused_114',['ImGuiInputEventAppFocused',['../d5/dd8/struct_im_gui_input_event_app_focused.html',1,'']]],
  ['imguiinputeventkey_115',['ImGuiInputEventKey',['../db/d5c/struct_im_gui_input_event_key.html',1,'']]],
  ['imguiinputeventmousebutton_116',['ImGuiInputEventMouseButton',['../dc/dd8/struct_im_gui_input_event_mouse_button.html',1,'']]],
  ['imguiinputeventmousepos_117',['ImGuiInputEventMousePos',['../d7/d2b/struct_im_gui_input_event_mouse_pos.html',1,'']]],
  ['imguiinputeventmouseviewport_118',['ImGuiInputEventMouseViewport',['../de/d82/struct_im_gui_input_event_mouse_viewport.html',1,'']]],
  ['imguiinputeventmousewheel_119',['ImGuiInputEventMouseWheel',['../d0/d89/struct_im_gui_input_event_mouse_wheel.html',1,'']]],
  ['imguiinputeventtext_120',['ImGuiInputEventText',['../d5/dca/struct_im_gui_input_event_text.html',1,'']]],
  ['imguiinputtextcallbackdata_121',['ImGuiInputTextCallbackData',['../da/d51/struct_im_gui_input_text_callback_data.html',1,'']]],
  ['imguiinputtextdeactivatedstate_122',['ImGuiInputTextDeactivatedState',['../d8/db2/struct_im_gui_input_text_deactivated_state.html',1,'']]],
  ['imguiinputtextstate_123',['ImGuiInputTextState',['../da/d59/struct_im_gui_input_text_state.html',1,'']]],
  ['imguiio_124',['ImGuiIO',['../d5/dbc/struct_im_gui_i_o.html',1,'']]],
  ['imguikeydata_125',['ImGuiKeyData',['../d2/dc3/struct_im_gui_key_data.html',1,'']]],
  ['imguikeyownerdata_126',['ImGuiKeyOwnerData',['../d6/d20/struct_im_gui_key_owner_data.html',1,'']]],
  ['imguikeyroutingdata_127',['ImGuiKeyRoutingData',['../dc/d72/struct_im_gui_key_routing_data.html',1,'']]],
  ['imguikeyroutingtable_128',['ImGuiKeyRoutingTable',['../d6/d75/struct_im_gui_key_routing_table.html',1,'']]],
  ['imguilastitemdata_129',['ImGuiLastItemData',['../da/d5e/struct_im_gui_last_item_data.html',1,'']]],
  ['imguilistclipper_130',['ImGuiListClipper',['../df/d0a/struct_im_gui_list_clipper.html',1,'']]],
  ['imguilistclipperdata_131',['ImGuiListClipperData',['../df/dfc/struct_im_gui_list_clipper_data.html',1,'']]],
  ['imguilistclipperrange_132',['ImGuiListClipperRange',['../df/d46/struct_im_gui_list_clipper_range.html',1,'']]],
  ['imguilocentry_133',['ImGuiLocEntry',['../d5/dbb/struct_im_gui_loc_entry.html',1,'']]],
  ['imguimenucolumns_134',['ImGuiMenuColumns',['../dc/d02/struct_im_gui_menu_columns.html',1,'']]],
  ['imguimetricsconfig_135',['ImGuiMetricsConfig',['../d3/d28/struct_im_gui_metrics_config.html',1,'']]],
  ['imguimultiselectio_136',['ImGuiMultiSelectIO',['../db/de3/struct_im_gui_multi_select_i_o.html',1,'']]],
  ['imguimultiselectstate_137',['ImGuiMultiSelectState',['../dd/d6a/struct_im_gui_multi_select_state.html',1,'']]],
  ['imguimultiselecttempdata_138',['ImGuiMultiSelectTempData',['../d7/d5d/struct_im_gui_multi_select_temp_data.html',1,'']]],
  ['imguinavitemdata_139',['ImGuiNavItemData',['../de/d6f/struct_im_gui_nav_item_data.html',1,'']]],
  ['imguinextitemdata_140',['ImGuiNextItemData',['../de/d0e/struct_im_gui_next_item_data.html',1,'']]],
  ['imguinextwindowdata_141',['ImGuiNextWindowData',['../d3/dd8/struct_im_gui_next_window_data.html',1,'']]],
  ['imguiobserver_142',['ImGuiObserver',['../df/d35/interface_im_gui_observer.html',1,'']]],
  ['imguioldcolumndata_143',['ImGuiOldColumnData',['../db/d99/struct_im_gui_old_column_data.html',1,'']]],
  ['imguioldcolumns_144',['ImGuiOldColumns',['../de/ded/struct_im_gui_old_columns.html',1,'']]],
  ['imguionceuponaframe_145',['ImGuiOnceUponAFrame',['../d4/da6/struct_im_gui_once_upon_a_frame.html',1,'']]],
  ['imguipayload_146',['ImGuiPayload',['../d7/d1d/struct_im_gui_payload.html',1,'']]],
  ['imguiplatformimedata_147',['ImGuiPlatformImeData',['../d8/dc8/struct_im_gui_platform_ime_data.html',1,'']]],
  ['imguiplatformio_148',['ImGuiPlatformIO',['../d0/d32/struct_im_gui_platform_i_o.html',1,'']]],
  ['imguiplatformmonitor_149',['ImGuiPlatformMonitor',['../d8/d1d/struct_im_gui_platform_monitor.html',1,'']]],
  ['imguiplotarraygetterdata_150',['ImGuiPlotArrayGetterData',['../d5/dc4/struct_im_gui_plot_array_getter_data.html',1,'']]],
  ['imguipopupdata_151',['ImGuiPopupData',['../da/d23/struct_im_gui_popup_data.html',1,'']]],
  ['imguiptrorindex_152',['ImGuiPtrOrIndex',['../d7/d84/struct_im_gui_ptr_or_index.html',1,'']]],
  ['imguiresizeborderdef_153',['ImGuiResizeBorderDef',['../d6/dd1/struct_im_gui_resize_border_def.html',1,'']]],
  ['imguiresizegripdef_154',['ImGuiResizeGripDef',['../d7/d0d/struct_im_gui_resize_grip_def.html',1,'']]],
  ['imguiselectionbasicstorage_155',['ImGuiSelectionBasicStorage',['../d2/d1c/struct_im_gui_selection_basic_storage.html',1,'']]],
  ['imguiselectionexternalstorage_156',['ImGuiSelectionExternalStorage',['../d7/dac/struct_im_gui_selection_external_storage.html',1,'']]],
  ['imguiselectionrequest_157',['ImGuiSelectionRequest',['../de/d3e/struct_im_gui_selection_request.html',1,'']]],
  ['imguisettingshandler_158',['ImGuiSettingsHandler',['../d2/d98/struct_im_gui_settings_handler.html',1,'']]],
  ['imguishrinkwidthitem_159',['ImGuiShrinkWidthItem',['../db/d9d/struct_im_gui_shrink_width_item.html',1,'']]],
  ['imguisizecallbackdata_160',['ImGuiSizeCallbackData',['../da/d8c/struct_im_gui_size_callback_data.html',1,'']]],
  ['imguistacklevelinfo_161',['ImGuiStackLevelInfo',['../da/dd0/struct_im_gui_stack_level_info.html',1,'']]],
  ['imguistorage_162',['ImGuiStorage',['../df/d15/struct_im_gui_storage.html',1,'']]],
  ['imguistoragepair_163',['ImGuiStoragePair',['../db/d0a/struct_im_gui_storage_pair.html',1,'']]],
  ['imguistyle_164',['ImGuiStyle',['../d7/d12/struct_im_gui_style.html',1,'']]],
  ['imguistylemod_165',['ImGuiStyleMod',['../d4/df8/struct_im_gui_style_mod.html',1,'']]],
  ['imguistylevarinfo_166',['ImGuiStyleVarInfo',['../db/df8/struct_im_gui_style_var_info.html',1,'']]],
  ['imguitabbar_167',['ImGuiTabBar',['../d5/d7d/struct_im_gui_tab_bar.html',1,'']]],
  ['imguitabbarsection_168',['ImGuiTabBarSection',['../dd/d2a/struct_im_gui_tab_bar_section.html',1,'']]],
  ['imguitabitem_169',['ImGuiTabItem',['../d3/d39/struct_im_gui_tab_item.html',1,'']]],
  ['imguitable_170',['ImGuiTable',['../da/d11/struct_im_gui_table.html',1,'']]],
  ['imguitablecelldata_171',['ImGuiTableCellData',['../d4/d22/struct_im_gui_table_cell_data.html',1,'']]],
  ['imguitablecolumn_172',['ImGuiTableColumn',['../d7/d8b/struct_im_gui_table_column.html',1,'']]],
  ['imguitablecolumnsettings_173',['ImGuiTableColumnSettings',['../da/daa/struct_im_gui_table_column_settings.html',1,'']]],
  ['imguitablecolumnsortspecs_174',['ImGuiTableColumnSortSpecs',['../d4/d36/struct_im_gui_table_column_sort_specs.html',1,'']]],
  ['imguitableheaderdata_175',['ImGuiTableHeaderData',['../d8/dfa/struct_im_gui_table_header_data.html',1,'']]],
  ['imguitableinstancedata_176',['ImGuiTableInstanceData',['../dc/d0a/struct_im_gui_table_instance_data.html',1,'']]],
  ['imguitablesettings_177',['ImGuiTableSettings',['../d2/dd0/struct_im_gui_table_settings.html',1,'']]],
  ['imguitablesortspecs_178',['ImGuiTableSortSpecs',['../d2/d81/struct_im_gui_table_sort_specs.html',1,'']]],
  ['imguitabletempdata_179',['ImGuiTableTempData',['../d1/d09/struct_im_gui_table_temp_data.html',1,'']]],
  ['imguitextbuffer_180',['ImGuiTextBuffer',['../da/d7d/struct_im_gui_text_buffer.html',1,'']]],
  ['imguitextfilter_181',['ImGuiTextFilter',['../d5/de6/struct_im_gui_text_filter.html',1,'']]],
  ['imguitextindex_182',['ImGuiTextIndex',['../df/d5b/struct_im_gui_text_index.html',1,'']]],
  ['imguitextrange_183',['ImGuiTextRange',['../d1/dde/struct_im_gui_text_filter_1_1_im_gui_text_range.html',1,'ImGuiTextFilter']]],
  ['imguitreenodestackdata_184',['ImGuiTreeNodeStackData',['../d0/dcb/struct_im_gui_tree_node_stack_data.html',1,'']]],
  ['imguitypingselectrequest_185',['ImGuiTypingSelectRequest',['../d2/dee/struct_im_gui_typing_select_request.html',1,'']]],
  ['imguitypingselectstate_186',['ImGuiTypingSelectState',['../dd/dac/struct_im_gui_typing_select_state.html',1,'']]],
  ['imguiviewport_187',['ImGuiViewport',['../d3/da6/struct_im_gui_viewport.html',1,'']]],
  ['imguiviewportdatametal_188',['ImGuiViewportDataMetal',['../d2/db2/struct_im_gui_viewport_data_metal.html',1,'']]],
  ['imguiviewportdataosx_189',['ImGuiViewportDataOSX',['../d4/d2c/struct_im_gui_viewport_data_o_s_x.html',1,'']]],
  ['imguiviewportp_190',['ImGuiViewportP',['../d7/dc4/struct_im_gui_viewport_p.html',1,'']]],
  ['imguiwindow_191',['ImGuiWindow',['../d6/d8f/struct_im_gui_window.html',1,'']]],
  ['imguiwindowclass_192',['ImGuiWindowClass',['../d4/d6c/struct_im_gui_window_class.html',1,'']]],
  ['imguiwindowdockstyle_193',['ImGuiWindowDockStyle',['../df/d90/struct_im_gui_window_dock_style.html',1,'']]],
  ['imguiwindowsettings_194',['ImGuiWindowSettings',['../d5/db5/struct_im_gui_window_settings.html',1,'']]],
  ['imguiwindowstackdata_195',['ImGuiWindowStackData',['../d1/d7e/struct_im_gui_window_stack_data.html',1,'']]],
  ['imguiwindowtempdata_196',['ImGuiWindowTempData',['../d3/d82/struct_im_gui_window_temp_data.html',1,'']]],
  ['imnewwrapper_197',['ImNewWrapper',['../dd/d6b/struct_im_new_wrapper.html',1,'']]],
  ['impool_198',['ImPool',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['impool_3c_20imguimultiselectstate_20_3e_199',['ImPool&lt; ImGuiMultiSelectState &gt;',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitabbar_20_3e_200',['ImPool&lt; ImGuiTabBar &gt;',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['impool_3c_20imguitable_20_3e_201',['ImPool&lt; ImGuiTable &gt;',['../d9/d6a/struct_im_pool.html',1,'']]],
  ['imrect_202',['ImRect',['../df/d8d/struct_im_rect.html',1,'']]],
  ['imspan_203',['ImSpan',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecelldata_20_3e_204',['ImSpan&lt; ImGuiTableCellData &gt;',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecolumn_20_3e_205',['ImSpan&lt; ImGuiTableColumn &gt;',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspan_3c_20imguitablecolumnidx_20_3e_206',['ImSpan&lt; ImGuiTableColumnIdx &gt;',['../d0/dbe/struct_im_span.html',1,'']]],
  ['imspanallocator_207',['ImSpanAllocator',['../d7/d2c/struct_im_span_allocator.html',1,'']]],
  ['imtriangulator_208',['ImTriangulator',['../df/da4/struct_im_triangulator.html',1,'']]],
  ['imtriangulatornode_209',['ImTriangulatorNode',['../d9/ddb/struct_im_triangulator_node.html',1,'']]],
  ['imtriangulatornodespan_210',['ImTriangulatorNodeSpan',['../dd/dd0/struct_im_triangulator_node_span.html',1,'']]],
  ['imvec1_211',['ImVec1',['../df/d59/struct_im_vec1.html',1,'']]],
  ['imvec2_212',['ImVec2',['../d7/d55/struct_im_vec2.html',1,'']]],
  ['imvec2ih_213',['ImVec2ih',['../d5/dc6/struct_im_vec2ih.html',1,'']]],
  ['imvec4_214',['ImVec4',['../de/d2a/struct_im_vec4.html',1,'']]],
  ['imvector_215',['ImVector',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_2a_20_3e_216',['ImVector&lt; char * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_3e_217',['ImVector&lt; char &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20const_20char_20_2a_20_3e_218',['ImVector&lt; const char * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20dxgi_5fswap_5fchain_5fdesc_20_3e_219',['ImVector&lt; DXGI_SWAP_CHAIN_DESC &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20exampleasset_20_3e_220',['ImVector&lt; ExampleAsset &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20exampletreenode_20_2a_20_3e_221',['ImVector&lt; ExampleTreeNode * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20float_20_3e_222',['ImVector&lt; float &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e_223',['ImVector&lt; ImDrawChannel &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e_224',['ImVector&lt; ImDrawCmd &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e_225',['ImVector&lt; ImDrawIdx &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_20_3e_226',['ImVector&lt; ImDrawList * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e_227',['ImVector&lt; ImDrawVert &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvertallegro_20_3e_228',['ImVector&lt; ImDrawVertAllegro &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_20_3e_229',['ImVector&lt; ImFont * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontatlascustomrect_20_3e_230',['ImVector&lt; ImFontAtlasCustomRect &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontbuildsrcglyphft_20_3e_231',['ImVector&lt; ImFontBuildSrcGlyphFT &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e_232',['ImVector&lt; ImFontConfig &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imfontglyph_20_3e_233',['ImVector&lt; ImFontGlyph &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkan_5fframerenderbuffers_20_3e_234',['ImVector&lt; ImGui_ImplVulkan_FrameRenderBuffers &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframe_20_3e_235',['ImVector&lt; ImGui_ImplVulkanH_Frame &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imgui_5fimplvulkanh_5fframesemaphores_20_3e_236',['ImVector&lt; ImGui_ImplVulkanH_FrameSemaphores &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolormod_20_3e_237',['ImVector&lt; ImGuiColorMod &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguicontexthook_20_3e_238',['ImVector&lt; ImGuiContextHook &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguidocknodesettings_20_3e_239',['ImVector&lt; ImGuiDockNodeSettings &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguidockrequest_20_3e_240',['ImVector&lt; ImGuiDockRequest &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguifocusscopedata_20_3e_241',['ImVector&lt; ImGuiFocusScopeData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e_242',['ImVector&lt; ImGuiGroupData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e_243',['ImVector&lt; ImGuiID &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiinputevent_20_3e_244',['ImVector&lt; ImGuiInputEvent &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiitemflags_20_3e_245',['ImVector&lt; ImGuiItemFlags &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguikeyroutingdata_20_3e_246',['ImVector&lt; ImGuiKeyRoutingData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguilistclipperdata_20_3e_247',['ImVector&lt; ImGuiListClipperData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguilistclipperrange_20_3e_248',['ImVector&lt; ImGuiListClipperRange &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguimultiselectstate_20_3e_249',['ImVector&lt; ImGuiMultiSelectState &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguimultiselecttempdata_20_3e_250',['ImVector&lt; ImGuiMultiSelectTempData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguioldcolumndata_20_3e_251',['ImVector&lt; ImGuiOldColumnData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguioldcolumns_20_3e_252',['ImVector&lt; ImGuiOldColumns &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiplatformmonitor_20_3e_253',['ImVector&lt; ImGuiPlatformMonitor &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguipopupdata_20_3e_254',['ImVector&lt; ImGuiPopupData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiptrorindex_20_3e_255',['ImVector&lt; ImGuiPtrOrIndex &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiselectionrequest_20_3e_256',['ImVector&lt; ImGuiSelectionRequest &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguisettingshandler_20_3e_257',['ImVector&lt; ImGuiSettingsHandler &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguishrinkwidthitem_20_3e_258',['ImVector&lt; ImGuiShrinkWidthItem &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistacklevelinfo_20_3e_259',['ImVector&lt; ImGuiStackLevelInfo &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistoragepair_20_3e_260',['ImVector&lt; ImGuiStoragePair &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e_261',['ImVector&lt; ImGuiStyleMod &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabbar_20_3e_262',['ImVector&lt; ImGuiTabBar &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabitem_20_3e_263',['ImVector&lt; ImGuiTabItem &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitable_20_3e_264',['ImVector&lt; ImGuiTable &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitablecolumnsortspecs_20_3e_265',['ImVector&lt; ImGuiTableColumnSortSpecs &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitableheaderdata_20_3e_266',['ImVector&lt; ImGuiTableHeaderData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitableinstancedata_20_3e_267',['ImVector&lt; ImGuiTableInstanceData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitabletempdata_20_3e_268',['ImVector&lt; ImGuiTableTempData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3aimguitextrange_20_3e_269',['ImVector&lt; ImGuiTextFilter::ImGuiTextRange &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguitreenodestackdata_20_3e_270',['ImVector&lt; ImGuiTreeNodeStackData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiviewport_20_2a_20_3e_271',['ImVector&lt; ImGuiViewport * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiviewportp_20_2a_20_3e_272',['ImVector&lt; ImGuiViewportP * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_20_3e_273',['ImVector&lt; ImGuiWindow * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindowstackdata_20_3e_274',['ImVector&lt; ImGuiWindowStackData &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e_275',['ImVector&lt; ImTextureID &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu16_20_3e_276',['ImVector&lt; ImU16 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu32_20_3e_277',['ImVector&lt; ImU32 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imu8_20_3e_278',['ImVector&lt; ImU8 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e_279',['ImVector&lt; ImVec2 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e_280',['ImVector&lt; ImVec4 &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e_281',['ImVector&lt; ImWchar &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20int_20_3e_282',['ImVector&lt; int &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20mydocument_20_2a_20_3e_283',['ImVector&lt; MyDocument * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20mydocument_20_3e_284',['ImVector&lt; MyDocument &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20sdl_5ffcolor_20_3e_285',['ImVector&lt; SDL_FColor &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamecontroller_20_2a_20_3e_286',['ImVector&lt; SDL_GameController * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20sdl_5fgamepad_20_2a_20_3e_287',['ImVector&lt; SDL_Gamepad * &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['imvector_3c_20unsigned_20char_20_3e_288',['ImVector&lt; unsigned char &gt;',['../df/d93/struct_im_vector.html',1,'']]],
  ['inombre_289',['INombre',['../d2/d35/class_c_e_1_1_i_nombre.html',1,'CE']]],
  ['inputbuffer_290',['InputBuffer',['../d0/d42/class_c_e_1_1_input_buffer.html',1,'CE']]],
  ['inputtextcallback_5fuserdata_291',['InputTextCallback_UserData',['../dc/d90/struct_input_text_callback___user_data.html',1,'']]],
  ['ipaths_292',['IPaths',['../da/d77/class_c_e_1_1_i_paths.html',1,'CE']]],
  ['irayo_293',['IRayo',['../d1/db4/class_i_v_j_1_1_i_rayo.html',1,'IVJ']]],
  ['irespawn_294',['IRespawn',['../da/d77/class_c_e_1_1_i_respawn.html',1,'CE']]],
  ['ishader_295',['IShader',['../d4/d4c/class_c_e_1_1_i_shader.html',1,'CE']]],
  ['isprite_296',['ISprite',['../da/d2f/class_c_e_1_1_i_sprite.html',1,'CE']]],
  ['istats_297',['IStats',['../d8/dde/class_c_e_1_1_i_stats.html',1,'CE']]],
  ['itexto_298',['ITexto',['../d4/d25/class_c_e_1_1_i_texto.html',1,'CE']]],
  ['itimer_299',['ITimer',['../d9/d72/class_c_e_1_1_i_timer.html',1,'CE']]],
  ['itransform_300',['ITransform',['../d5/d49/class_c_e_1_1_i_transform.html',1,'CE']]],
  ['itriangulo_301',['ITriangulo',['../d5/d95/class_i_v_j_1_1_i_triangulo.html',1,'IVJ']]]
];
